/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;


import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Finance.AccountManagement;
import Business.Network.Network;
import Business.Organization.BorrowerOrganization;
import Business.Organization.Organization;
import Business.Person.Borrower;
import Business.Role.BorrowerRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author shwetatatiya
 */
public class BorrowerSignUpJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer ;
    private EcoSystem system ;
    /**
     * Creates new form SignUpBorrowerJPanel
     */
    
    
    public BorrowerSignUpJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer ;
        this.system = system ;
        populateNetworkComboBox();
        
    }
    
    public void populateNetworkComboBox(){
    networkComboBox1.removeAllItems();
    for(Network network : system.getNetworkList()){

    networkComboBox1.addItem(network);

    }
}

    public void populateEnterpriseComboBox(Network network){

    enterpriseComboBox1.removeAllItems();

    for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){

    enterpriseComboBox1.addItem(enterprise);
}
}     

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBorrowerName = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtBorrowerOccupation = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtBorrowerAddress = new javax.swing.JTextArea();
        txtBorrowerPassword = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtBorrowerUserName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtBorrowerCountry = new javax.swing.JTextField();
        txtBorrowerEmailId = new javax.swing.JTextField();
        txtBorrowerPhoneNo = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        networkComboBox1 = new javax.swing.JComboBox();
        btnSignUp1 = new javax.swing.JButton();
        enterpriseComboBox1 = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        txtBorrowerYearlyIncome = new javax.swing.JTextField();

        setBackground(new java.awt.Color(102, 0, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBorrowerName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        add(txtBorrowerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 281, -1));

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("OCCUPATION");
        jLabel14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 551, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(" PASSWORD ");
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, -1, -1));

        txtBorrowerOccupation.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        add(txtBorrowerOccupation, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 561, 281, -1));

        txtBorrowerAddress.setColumns(20);
        txtBorrowerAddress.setRows(5);
        txtBorrowerAddress.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        jScrollPane1.setViewportView(txtBorrowerAddress);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 441, 281, -1));

        txtBorrowerPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        add(txtBorrowerPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 280, 30));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText(" ADDRESS ");
        jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 431, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" USERNAME ");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("  BORROWER SIGN UP PAGE ");
        jLabel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        txtBorrowerUserName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        add(txtBorrowerUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 281, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(" EMAIL ");
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 241, -1, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" NAME ");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 74, -1, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("YEARLY INCOME:");
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 600, -1, -1));

        btnBack.setBackground(new java.awt.Color(153, 153, 153));
        btnBack.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        btnBack.setText("<< BACK");
        btnBack.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 810, 190, 60));

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText(" COUNTRY ");
        jLabel13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 371, -1, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText(" PHONE ");
        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 311, -1, -1));

        txtBorrowerCountry.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        add(txtBorrowerCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 381, 281, -1));

        txtBorrowerEmailId.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        add(txtBorrowerEmailId, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 241, 281, -1));

        txtBorrowerPhoneNo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        add(txtBorrowerPhoneNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 311, 281, -1));

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("REGION/NETWORK:");
        jLabel15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 693, -1, -1));

        networkComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        networkComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkComboBox1ActionPerformed(evt);
            }
        });
        add(networkComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 693, 281, -1));

        btnSignUp1.setBackground(new java.awt.Color(153, 153, 153));
        btnSignUp1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        btnSignUp1.setText("SIGN UP");
        btnSignUp1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        btnSignUp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUp1ActionPerformed(evt);
            }
        });
        add(btnSignUp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 810, 268, 58));

        enterpriseComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(enterpriseComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 750, 281, -1));

        jLabel16.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("ENTERPRISE:");
        jLabel16.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 743, -1, -1));

        txtBorrowerYearlyIncome.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        add(txtBorrowerYearlyIncome, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 622, 270, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void networkComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkComboBox1ActionPerformed
        // TODO add your handling code here:
        Network network = (Network) networkComboBox1.getSelectedItem();
        if(network != null)
        {populateEnterpriseComboBox(network);}
    }//GEN-LAST:event_networkComboBox1ActionPerformed

    private void btnSignUp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUp1ActionPerformed
        // TODO add your handling code here:
        String name = txtBorrowerName.getText();
        String userName = txtBorrowerUserName.getText();
        String password = txtBorrowerPassword.getText();
        String emailId = txtBorrowerEmailId.getText();
        String address = txtBorrowerAddress.getText();
        String phoneNo = txtBorrowerPhoneNo.getText();
        String occupation = txtBorrowerOccupation.getText();
        int income = 0;

        if(name.trim() == "" ||
            userName.trim() == "" ||
            password.trim() == "" ||
            emailId.trim() == "" ||
            address.trim() == "" ||
            phoneNo.trim() == ""){
            JOptionPane.showMessageDialog(null, "Please enter all required details", "Information", JOptionPane.INFORMATION_MESSAGE);
            return ;
        }

        if(!Enterprise.containsOnlyDigits(phoneNo)){
            JOptionPane.showMessageDialog(null, "Please enter only digits for Phone", "Information", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if(!(txtBorrowerYearlyIncome.getText() == "")){
            if(Enterprise.containsOnlyDigits(txtBorrowerYearlyIncome.getText())){
                income = Integer.parseInt(txtBorrowerYearlyIncome.getText());
            }else {
                JOptionPane.showMessageDialog(null, "Please enter only digits for income", "Information", JOptionPane.INFORMATION_MESSAGE);
                return;
            }}

            if(!EcoSystem.checkIfUserNameIsUnique(userName))
            {
                JOptionPane.showMessageDialog(null, "This username already exists", "Informaton", JOptionPane.INFORMATION_MESSAGE);
                return ;
            }

            Borrower borrower = new Borrower();
            borrower.setAccountManagement(new AccountManagement());
         //   borrower.setAddress(address.trim());
            borrower.setName(name.trim());

            borrower.setYearlyIncome(income);
            borrower.setEmailId(emailId.trim());
            borrower.setPhoneNo(phoneNo.trim());
            borrower.setOccupation(occupation);

            Enterprise enterprise = (Enterprise) enterpriseComboBox1.getSelectedItem();
            for(Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
                if(organization instanceof BorrowerOrganization){
                    BorrowerOrganization borrowerOrganization = (BorrowerOrganization) organization ;
                    borrowerOrganization.getPersonDirectory().addPerson(borrower);
                    UserAccount userAccount = borrowerOrganization.getUserAccountDirectory().createUserAccount(userName.trim(), password.trim(), new BorrowerRole()) ;
                    borrower.setUserAccount(userAccount);
                    JOptionPane.showMessageDialog(null,  "Account created successfully","Information", JOptionPane.INFORMATION_MESSAGE);
                    DB4OUtil.getInstance().storeSystem(system);
                    return ;
                }
            }

            JOptionPane.showMessageDialog(null,  "Account could not be created. Please try again","Information", JOptionPane.INFORMATION_MESSAGE);

            return ;
    }//GEN-LAST:event_btnSignUp1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSignUp1;
    private javax.swing.JComboBox enterpriseComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox networkComboBox1;
    private javax.swing.JTextArea txtBorrowerAddress;
    private javax.swing.JTextField txtBorrowerCountry;
    private javax.swing.JTextField txtBorrowerEmailId;
    private javax.swing.JTextField txtBorrowerName;
    private javax.swing.JTextField txtBorrowerOccupation;
    private javax.swing.JPasswordField txtBorrowerPassword;
    private javax.swing.JTextField txtBorrowerPhoneNo;
    private javax.swing.JTextField txtBorrowerUserName;
    private javax.swing.JTextField txtBorrowerYearlyIncome;
    // End of variables declaration//GEN-END:variables
}
