/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.FieldPartner.GeneralInformation;
import Business.FieldPartner.PerformanceInformation;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.RepresentativeOrganization;
import Business.Organization.TrusteeOrganization;
import Business.Person.FieldPartnerContact;
import Business.Person.Person;
import Business.WorkQueue.NewFieldPartnerWorkRequest;
import java.awt.CardLayout;
import java.util.Enumeration;

import javax.swing.AbstractButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author shwetatatiya
 */
public class FieldPartnerFormJPanel extends javax.swing.JPanel {

   private JPanel userProcessContainer ;
    private EcoSystem system ;
    /**
     * Creates new form BorrowerFormJPanel
     */
    

    FieldPartnerFormJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer ;
        this.system = system ;
        jRadioButton1.setSelected(true);
        populateNetworkComboBox();
        
    }
    
    public void populateNetworkComboBox(){
    networkComboBox.removeAllItems();
    for(Network network : system.getNetworkList()){

    networkComboBox.addItem(network);

    }
}

    public void populateEnterpriseComboBox(Network network){

    enterpriseComboBox.removeAllItems();

    for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){

    enterpriseComboBox.addItem(enterprise);
}
}    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtFieldPartnerOrganizationName = new javax.swing.JTextField();
        txtFieldPartnerorganizationWebsite = new javax.swing.JTextField();
        txtFieldPartnerPrimaryCountryOperation = new javax.swing.JTextField();
        txtReferencePerson = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtFieldPartnerContactPersonName = new javax.swing.JTextField();
        txtFieldPartnerContactPersonJobTitle = new javax.swing.JTextField();
        txtFieldPartnerContactPersonEmailId = new javax.swing.JTextField();
        txtFieldPartnerContactPersonPhoneNo = new javax.swing.JTextField();
        btnFieldPartnerSignUp = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtFieldPartnerHeadquartersAddress = new javax.swing.JTextArea();
        btnBack = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtFieldPartnerMissionStatement = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        networkComboBox = new javax.swing.JComboBox();
        enterpriseComboBox = new javax.swing.JComboBox();
        txtFieldPartnerImpactArea = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setForeground(new java.awt.Color(153, 153, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("HELPING HANDS PARTNERSHIP APPLICATION ");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" ORGANIZATION NAME ");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 230, 30));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(" ORGANIZATION WEBSITE ");
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(" HEADQUARTERS ADDRESS ");
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText(" PRIMARY COUNTRY ");
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText(" ORGANIZATION INFORMATION ");
        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 586, -1, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText(" LEGAL STATUS ");
        jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 655, -1, -1));

        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("NGO IN USA");
        jRadioButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 643, -1, -1));

        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Bank");
        jRadioButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 643, -1, -1));

        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("LLC");
        jRadioButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jPanel1.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 673, -1, -1));

        jRadioButton4.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton4.setText("Non-Bank Financial Institution");
        jRadioButton4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 673, -1, -1));

        jRadioButton5.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton5.setText("CO-OPERATIVE");
        jRadioButton5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jPanel1.add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 703, -1, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText(" IMPACT AREA ");
        jLabel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 767, -1, -1));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("REFERENCE PERSON (IF ANY) ");
        jLabel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 811, -1, -1));

        txtFieldPartnerOrganizationName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        jPanel1.add(txtFieldPartnerOrganizationName, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 341, 30));

        txtFieldPartnerorganizationWebsite.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        jPanel1.add(txtFieldPartnerorganizationWebsite, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 350, 30));

        txtFieldPartnerPrimaryCountryOperation.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        jPanel1.add(txtFieldPartnerPrimaryCountryOperation, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 350, 30));

        txtReferencePerson.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        jPanel1.add(txtReferencePerson, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 810, 290, 30));

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText(" CONTACT PERSON DETAILS ");
        jLabel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 170, -1, -1));

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText(" NAME ");
        jLabel11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 240, -1, -1));

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText(" JOB TITLE ");
        jLabel12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 290, -1, -1));

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText(" EMAIL ");
        jLabel13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 340, -1, -1));

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText(" PHONE ");
        jLabel14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 390, -1, -1));

        txtFieldPartnerContactPersonName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        jPanel1.add(txtFieldPartnerContactPersonName, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 240, 188, -1));

        txtFieldPartnerContactPersonJobTitle.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        jPanel1.add(txtFieldPartnerContactPersonJobTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 290, 188, -1));

        txtFieldPartnerContactPersonEmailId.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        jPanel1.add(txtFieldPartnerContactPersonEmailId, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 340, 188, -1));

        txtFieldPartnerContactPersonPhoneNo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        jPanel1.add(txtFieldPartnerContactPersonPhoneNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 390, 188, -1));

        btnFieldPartnerSignUp.setBackground(new java.awt.Color(0, 0, 0));
        btnFieldPartnerSignUp.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        btnFieldPartnerSignUp.setForeground(new java.awt.Color(255, 255, 255));
        btnFieldPartnerSignUp.setText("SUBMIT >>");
        btnFieldPartnerSignUp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 6, true));
        btnFieldPartnerSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFieldPartnerSignUpActionPerformed(evt);
            }
        });
        jPanel1.add(btnFieldPartnerSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 972, 250, 66));

        txtFieldPartnerHeadquartersAddress.setColumns(20);
        txtFieldPartnerHeadquartersAddress.setRows(5);
        txtFieldPartnerHeadquartersAddress.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        jScrollPane2.setViewportView(txtFieldPartnerHeadquartersAddress);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 341, -1));

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<< BACK");
        btnBack.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 6, true));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 972, 190, 66));

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText(" MISSION STATEMENT ");
        jLabel15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, -1, -1));

        txtFieldPartnerMissionStatement.setColumns(20);
        txtFieldPartnerMissionStatement.setRows(5);
        txtFieldPartnerMissionStatement.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        jScrollPane3.setViewportView(txtFieldPartnerMissionStatement);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, 341, -1));
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(919, 0, -1, -1));

        jLabel17.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText(" OF OPERATION ");
        jLabel17.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jLabel18.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText(" REGION/NETWORK ");
        jLabel18.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 869, -1, -1));

        jLabel19.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText(" ENTERPRISE ");
        jLabel19.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 918, -1, -1));

        networkComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        networkComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(networkComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 870, 274, -1));

        enterpriseComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(enterpriseComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 910, 274, -1));

        txtFieldPartnerImpactArea.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        txtFieldPartnerImpactArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldPartnerImpactAreaActionPerformed(evt);
            }
        });
        jPanel1.add(txtFieldPartnerImpactArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 760, 290, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1231, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1038, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void btnFieldPartnerSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFieldPartnerSignUpActionPerformed
        // TODO add your handling code here:
        // Validations and exception handling done

        RepresentativeOrganization representativeOrganization = null;
        Enterprise enterprise;
        Employee ref = null;
        enterprise = (Enterprise) enterpriseComboBox.getSelectedItem();

        String contactName = txtFieldPartnerContactPersonName.getText();
        String jobTitle = txtFieldPartnerContactPersonJobTitle.getText();
        String email = txtFieldPartnerContactPersonEmailId.getText();
        String phone = txtFieldPartnerContactPersonPhoneNo.getText();

        String orgName = txtFieldPartnerOrganizationName.getText();
        String website = txtFieldPartnerorganizationWebsite.getText();
        String countryOfOperation = txtFieldPartnerPrimaryCountryOperation.getText();
        String address = txtFieldPartnerHeadquartersAddress.getText();
        String mission = txtFieldPartnerMissionStatement.getText();

        if(contactName.trim() == "" || jobTitle.trim() == "" || email.trim() == "" || phone.trim()== "" ||
            orgName.trim() == "" || website.trim() == "" || countryOfOperation.trim() == "" ||
            address.trim() == "" || mission.trim() == ""){
            JOptionPane.showMessageDialog(null, "Please enter all the details in the form", "Information", JOptionPane.INFORMATION_MESSAGE);
            return ;}

        if(!Enterprise.containsOnlyDigits(phone.trim())){
            JOptionPane.showMessageDialog(null, "Please enter only digits as phone", "Information", JOptionPane.INFORMATION_MESSAGE);
            return ;
        }

        String refPerson = txtReferencePerson.getText();

        if(refPerson != ""){
            for(Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
                if(organization instanceof RepresentativeOrganization ||
                    organization instanceof TrusteeOrganization){
                    for(Person person : organization.getPersonDirectory().getPersonList()){
                        if(person.getName().equals(refPerson)){
                            ref = (Employee)person ;
                            break ;
                        }
                    }
                    if(ref != null) break;
                }}
            }

            String impactArea = txtFieldPartnerImpactArea.getText();
            String legalStatus = "";

            for (Enumeration<AbstractButton> buttons = fieldPartnerLegalStatusButtonGroup.getElements(); buttons.hasMoreElements();) {
                AbstractButton button = buttons.nextElement();

                if (button.isSelected()) {
                    legalStatus = button.getText();
                    break ;
                }
            }

            if(impactArea.trim() == ""){
                JOptionPane.showMessageDialog(null, "Please enter the impact area", "Information", JOptionPane.INFORMATION_MESSAGE);
                return ;}

            GeneralInformation generalInformation = new GeneralInformation(orgName.trim(), website.trim(), address.trim(), countryOfOperation.trim(),
                legalStatus.trim(), ref, mission.trim(), impactArea.trim());
            PerformanceInformation performanceInformation = new PerformanceInformation();

            FieldPartnerContact fieldPartnerContact = new FieldPartnerContact();
            fieldPartnerContact.setName(contactName.trim());
            fieldPartnerContact.setJobTitle(jobTitle.trim());
            fieldPartnerContact.setEmail(email.trim());
            fieldPartnerContact.setPhone(phone.trim());

            // Create Work Request and send to Analyst Orgnization work Queue

            NewFieldPartnerWorkRequest fieldPartnerWorkRequest = new NewFieldPartnerWorkRequest(generalInformation, performanceInformation, fieldPartnerContact);
            fieldPartnerWorkRequest.setMessage("Application for a new Field Partner");
            for(Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
                if(organization instanceof RepresentativeOrganization) representativeOrganization = (RepresentativeOrganization)organization ;
            }

            fieldPartnerWorkRequest.pushToOrganizationWorkQueue(representativeOrganization);

            JOptionPane.showMessageDialog(null, "Application submited", "Information", JOptionPane.INFORMATION_MESSAGE);

            DB4OUtil.getInstance().storeSystem(system);

    }//GEN-LAST:event_btnFieldPartnerSignUpActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void networkComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkComboBoxActionPerformed
        // TODO add your handling code here:
        Network network = (Network) networkComboBox.getSelectedItem();

        if(network != null){
            populateEnterpriseComboBox(network);
        }
    }//GEN-LAST:event_networkComboBoxActionPerformed

    private void txtFieldPartnerImpactAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldPartnerImpactAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldPartnerImpactAreaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnFieldPartnerSignUp;
    private javax.swing.JComboBox enterpriseComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox networkComboBox;
    private javax.swing.JTextField txtFieldPartnerContactPersonEmailId;
    private javax.swing.JTextField txtFieldPartnerContactPersonJobTitle;
    private javax.swing.JTextField txtFieldPartnerContactPersonName;
    private javax.swing.JTextField txtFieldPartnerContactPersonPhoneNo;
    private javax.swing.JTextArea txtFieldPartnerHeadquartersAddress;
    private javax.swing.JTextField txtFieldPartnerImpactArea;
    private javax.swing.JTextArea txtFieldPartnerMissionStatement;
    private javax.swing.JTextField txtFieldPartnerOrganizationName;
    private javax.swing.JTextField txtFieldPartnerPrimaryCountryOperation;
    private javax.swing.JTextField txtFieldPartnerorganizationWebsite;
    private javax.swing.JTextField txtReferencePerson;
    // End of variables declaration//GEN-END:variables
}
