/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Finance.AccountManagement;
import Business.Finance.MoneyBasket;
import Business.Network.Network;
import Business.Organization.LenderOrganization;
import Business.Organization.Organization;
import Business.Person.Lender;
import Business.Role.LenderRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author shwetatatiya
 */
public class LenderSignUpJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer ;
    private EcoSystem system ;
    /**
     * Creates new form SignInLenderJPanel
     */
   
    
    public LenderSignUpJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer ;
        this.system = system ;
        populateNetworkComboBox();
        
    }
    
    public void populateNetworkComboBox(){
    networkComboBox.removeAllItems();
    for(Network network : system.getNetworkList()){

    networkComboBox.addItem(network);

    }
}

    public void populateEnterpriseComboBox(Network network){

    enterpriseComboBox.removeAllItems();

    for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){

    enterpriseComboBox.addItem(enterprise);
}
}  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtLenderName = new javax.swing.JTextField();
        networkComboBox = new javax.swing.JComboBox();
        txtLenderUserName = new javax.swing.JTextField();
        enterpriseComboBox = new javax.swing.JComboBox();
        txtLenderEmailId = new javax.swing.JTextField();
        txtLenderPhoneNo = new javax.swing.JTextField();
        txtLenderPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLenderAddress = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnSignUp = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(" EMAIL ");
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 255, -1, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText(" PHONE ");
        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 321, -1, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText(" ADDRESS ");
        jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 399, -1, -1));

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText(" REGION/NETWORK ");
        jLabel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 513, -1, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("  LENDER SIGN UP PAGE");
        jLabel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 6, true));
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 0, 480, -1));

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText(" ENTERPRISE ");
        jLabel11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 578, -1, -1));

        txtLenderName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        add(txtLenderName, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 65, 281, -1));

        networkComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        networkComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkComboBoxActionPerformed(evt);
            }
        });
        add(networkComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 517, -1, -1));

        txtLenderUserName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        add(txtLenderUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 128, 281, -1));

        enterpriseComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(enterpriseComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 579, -1, -1));

        txtLenderEmailId.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        add(txtLenderEmailId, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 259, 281, -1));

        txtLenderPhoneNo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        add(txtLenderPhoneNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 325, 281, -1));

        txtLenderPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        add(txtLenderPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 197, 281, 28));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" NAME ");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 61, -1, -1));

        txtLenderAddress.setColumns(20);
        txtLenderAddress.setRows(5);
        txtLenderAddress.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        jScrollPane1.setViewportView(txtLenderAddress);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 399, 576, 96));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" USERNAME ");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 124, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(" PASSWORD ");
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 195, -1, -1));

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<< BACK");
        btnBack.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 626, 248, 66));

        btnSignUp.setBackground(new java.awt.Color(0, 0, 0));
        btnSignUp.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        btnSignUp.setForeground(new java.awt.Color(255, 255, 255));
        btnSignUp.setText("SIGN UP");
        btnSignUp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });
        add(btnSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 626, 274, 66));
    }// </editor-fold>//GEN-END:initComponents

    private void networkComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkComboBoxActionPerformed
        // TODO add your handling code here:
        Network network = (Network) networkComboBox.getSelectedItem();
        if(network != null)
        {populateEnterpriseComboBox(network);}
    }//GEN-LAST:event_networkComboBoxActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String name = txtLenderName.getText();
        String userName = txtLenderUserName.getText();
        String password = txtLenderPassword.getText();
        String emailId = txtLenderEmailId.getText();
        String address = txtLenderAddress.getText();
        String phoneNo = txtLenderPhoneNo.getText();

        if(name.trim() == "" ||
            userName.trim() == "" ||
            password.trim() == "" ||
            emailId.trim() == "" ||
            address.trim() == "" ||
            phoneNo.trim() == ""){
            JOptionPane.showMessageDialog(null, "Please enter all details", "Informaton", JOptionPane.INFORMATION_MESSAGE);
            return ;
        }

        if(!Enterprise.containsOnlyDigits(phoneNo)){
            JOptionPane.showMessageDialog(null, "Please enter only digits in phone", "Informaton", JOptionPane.INFORMATION_MESSAGE);
            return ;
        }

        if(!EcoSystem.checkIfUserNameIsUnique(userName))
        {
            JOptionPane.showMessageDialog(null, "This username already exists", "Informaton", JOptionPane.INFORMATION_MESSAGE);
            return ;
        }

        Lender lender = new Lender();
        lender.setAccountManagement(new AccountManagement());
        lender.setMoneyBasket(new MoneyBasket()) ;
     //   lender.setAddress(address.trim());
        lender.setName(name.trim());
        lender.setEmail(emailId.trim());
        lender.setPhone(phoneNo.trim());

        Enterprise enterprise = (Enterprise) enterpriseComboBox.getSelectedItem();
        for(Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if(organization instanceof LenderOrganization){
                LenderOrganization lenderOrganization = (LenderOrganization) organization ;
                lenderOrganization.getPersonDirectory().addPerson(lender);
                UserAccount userAccount = lenderOrganization.getUserAccountDirectory().createUserAccount(userName.trim(), password.trim(), new LenderRole()) ;
                lender.setUserAccount(userAccount);
                JOptionPane.showMessageDialog(null,  "Account created successfully","Information", JOptionPane.INFORMATION_MESSAGE);
                DB4OUtil.getInstance().storeSystem(system);
                return ;
            }
        }

        JOptionPane.showMessageDialog(null,  "Account could not be created. Please try again","Information", JOptionPane.INFORMATION_MESSAGE);
        return ;
    }//GEN-LAST:event_btnSignUpActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JComboBox enterpriseComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox networkComboBox;
    private javax.swing.JTextArea txtLenderAddress;
    private javax.swing.JTextField txtLenderEmailId;
    private javax.swing.JTextField txtLenderName;
    private javax.swing.JPasswordField txtLenderPassword;
    private javax.swing.JTextField txtLenderPhoneNo;
    private javax.swing.JTextField txtLenderUserName;
    // End of variables declaration//GEN-END:variables
}
