/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.EcoSystem;
import java.awt.CardLayout;
import static java.time.Clock.system;
import javax.swing.JPanel;

/**
 *
 * @author shwetatatiya
 */
public class SignUpJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SignUpJPanel
     */
    private JPanel userProcessContainer ;
    private EcoSystem system ;
    public SignUpJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer ;
        this.system = system ;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSignUpBorrower = new javax.swing.JButton();
        btnSignUpLender = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSignUpBorrower.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        btnSignUpBorrower.setForeground(new java.awt.Color(255, 255, 255));
        btnSignUpBorrower.setText("SIGN UP AS A BORROWER >>");
        btnSignUpBorrower.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 6, true));
        btnSignUpBorrower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpBorrowerActionPerformed(evt);
            }
        });
        add(btnSignUpBorrower, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 480, 90));

        btnSignUpLender.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        btnSignUpLender.setForeground(new java.awt.Color(255, 255, 255));
        btnSignUpLender.setText("SIGN UP AS A LENDER >>");
        btnSignUpLender.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 6, true));
        btnSignUpLender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpLenderActionPerformed(evt);
            }
        });
        add(btnSignUpLender, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 480, 90));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("  SIGN UP FOR HELPING HANDS");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 6, true));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 30, 610, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignUpBorrowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpBorrowerActionPerformed
        // TODO add your handling code here:
        BorrowerSignUpJPanel borrowerSignUpJPanel = new BorrowerSignUpJPanel(userProcessContainer, system);
        userProcessContainer.add("BorrowerSignUpJPanel", borrowerSignUpJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnSignUpBorrowerActionPerformed

    private void btnSignUpLenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpLenderActionPerformed
        // TODO add your handling code here:
        LenderSignUpJPanel lenderSignUpJPanel = new LenderSignUpJPanel(userProcessContainer, system);
        userProcessContainer.add("LenderSignUpJPanel", lenderSignUpJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnSignUpLenderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSignUpBorrower;
    private javax.swing.JButton btnSignUpLender;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
