/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.LenderRole;

import Business.Enterprise.Enterprise;
import Business.Enterprise.HelpingHandsEnterprise;
import Business.Finance.MoneyBasket;
import Business.Loan.LendingInstance;
import Business.Loan.Loan;
import Business.Loan.LoanCase;
import Business.Loan.LoanCase.Category;
import Business.Person.Lender;
import Business.UserAccount.UserAccount;
import UserInterface.MoneyBasket.MoneyBasketJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Shrutik
 */
public class LenderWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LenderWorkAreaJPanel
     */
    
    private JPanel userProcessContainer ;
    private HelpingHandsEnterprise business ;
    private UserAccount userAccount ;
    private Lender lender;
    
    public LenderWorkAreaJPanel(JPanel userProcessContainer, Enterprise business, UserAccount account, Lender lender) {
        initComponents();
        this.userProcessContainer = userProcessContainer ;
        this.business = (HelpingHandsEnterprise) business ;
        this.userAccount = userAccount ;
        this.lender = lender ;
        populateCategoryComboBox();
        populateCreditComboBox();
        populateAvailableCredit();
        populateOutstanding();
    }

    
    public void populateCategoryComboBox() 
    {
        categoryComboBox.removeAllItems();
        
        for(Category category : LoanCase.Category.values())
        {
            categoryComboBox.addItem(category);
        }
       
    } 
    
    public void populateCreditComboBox(){
        int[] amount = {25, 50, 100, 150, 200, 500, 1000, 1500, 1750, 2000, 5000};
        
        creditComboBox.removeAllItems();
        for(int i = 0; i<amount.length; i++){
            creditComboBox.addItem(amount[i]);
        }
    }
    
    public void populateTblLoanCases(String category)
    {
         DefaultTableModel model = (DefaultTableModel) tblLoanCases.getModel();
          model.setRowCount(0);
          /*BorrowerOrganization bo = business.getBorrowerOrganization();
          
          for(Person person : bo.getPersonDirectory().getPersonList())
          {   
              Borrower borrower = (Borrower)person ;
              Object row [] = new Object[3];
              row[0] = person;
              row[1] = borrower.getLoan().getLoanCase().getLoanAmount();
              row[2] = borrower.getLoan().getLoanCase().getLoanLength();
              model.addRow(row);
              
          }*/
          
          for(Loan loan : business.getLoanDirectory().getLoanList()){
              if(loan.getLoanStatus().equals(Loan.LoanStatus.FundingNeeded) ||
                 loan.getLoanStatus().equals(Loan.LoanStatus.PartlyFunded)){
                  if(loan.getLoanCase().getCategory().getValue().equals(category)){
                Object row [] = new Object[3];
                row[0] = loan;
                row[1] = loan.getLoanCase().getLoanAmount();
                row[2] = loan.getLoanCase().getLoanLength();
                model.addRow(row);                      
                  }
              }
          }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        lblcountry = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        categoryComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLoanCases = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        btnProceed = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblLoanCases1 = new javax.swing.JTable();
        btnAdd1 = new javax.swing.JButton();
        btnView1 = new javax.swing.JButton();
        btnProceed1 = new javax.swing.JButton();
        categoryComboBox1 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnAddCredit = new javax.swing.JButton();
        lblname1 = new javax.swing.JLabel();
        lblcountry1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtCurrentBalance = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtOutstanding = new javax.swing.JTextField();
        creditComboBox = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("  LENDER DASHBOARD  ");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        lblname.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lblname.setForeground(new java.awt.Color(255, 255, 255));
        lblname.setText("NAME");

        lblcountry.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lblcountry.setForeground(new java.awt.Color(255, 255, 255));
        lblcountry.setText("COUNTRY");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("  CATEGORIES  ");
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        categoryComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        categoryComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryComboBoxActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("  BORROWER DETAILS  ");
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        tblLoanCases.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Borrower", "Loan Amount", "Loan Length"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblLoanCases);

        btnAdd.setBackground(new java.awt.Color(0, 0, 0));
        btnAdd.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("ADD BORROWER >>");
        btnAdd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnView.setBackground(new java.awt.Color(0, 0, 0));
        btnView.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnView.setForeground(new java.awt.Color(255, 255, 255));
        btnView.setText("VIEW LOAN CASE >>");
        btnView.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnProceed.setBackground(new java.awt.Color(0, 0, 0));
        btnProceed.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        btnProceed.setForeground(new java.awt.Color(255, 255, 255));
        btnProceed.setText("PROCEED TO CHECKOUT >>");
        btnProceed.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        btnProceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProceedActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("  LENDER DASHBOARD  ");
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("  CATEGORIES  ");
        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("  BORROWER DETAILS  ");
        jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        tblLoanCases1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Borrower", "Loan Amount", "Loan Length"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblLoanCases1);

        btnAdd1.setBackground(new java.awt.Color(0, 0, 0));
        btnAdd1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnAdd1.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd1.setText("ADD BORROWER >>");
        btnAdd1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        btnAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd1ActionPerformed(evt);
            }
        });

        btnView1.setBackground(new java.awt.Color(0, 0, 0));
        btnView1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnView1.setForeground(new java.awt.Color(255, 255, 255));
        btnView1.setText("VIEW LOAN CASE >>");
        btnView1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        btnView1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnView1ActionPerformed(evt);
            }
        });

        btnProceed1.setBackground(new java.awt.Color(0, 0, 0));
        btnProceed1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        btnProceed1.setForeground(new java.awt.Color(255, 255, 255));
        btnProceed1.setText("PROCEED TO CHECKOUT >>");
        btnProceed1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        btnProceed1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProceed1ActionPerformed(evt);
            }
        });

        categoryComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        categoryComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryComboBox1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("  ADD CREDIT TO YOUR ACCOUNT  ");
        jLabel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        btnAddCredit.setBackground(new java.awt.Color(0, 0, 0));
        btnAddCredit.setForeground(new java.awt.Color(255, 255, 255));
        btnAddCredit.setText("ADD >>");
        btnAddCredit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        btnAddCredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCreditActionPerformed(evt);
            }
        });

        lblname1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lblname1.setForeground(new java.awt.Color(255, 255, 255));
        lblname1.setText("NAME");

        lblcountry1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lblcountry1.setForeground(new java.awt.Color(255, 255, 255));
        lblcountry1.setText("COUNTRY");

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("  CURRENT BALANCE AVAILABLE  ");
        jLabel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        txtCurrentBalance.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("OUTSTANDING LOANS");
        jLabel11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        txtOutstanding.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        creditComboBox.setForeground(new java.awt.Color(255, 255, 255));
        creditComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(54, 54, 54)
                                                .addComponent(categoryComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(307, 307, 307))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnProceed1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addComponent(jLabel8))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnView1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(creditComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnAddCredit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtOutstanding, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(113, 113, 113)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(txtCurrentBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel5)
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblname1)
                            .addComponent(lblcountry1))
                        .addGap(172, 172, 172)
                        .addComponent(jLabel12)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblname1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblcountry1)))))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(categoryComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnView1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProceed1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddCredit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(creditComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCurrentBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel10))
                .addGap(106, 106, 106)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(txtOutstanding, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(223, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(btnProceed, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(217, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jLabel2)
                            .addGap(54, 54, 54)
                            .addComponent(lblname))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(510, 510, 510)
                            .addComponent(lblcountry))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(34, 34, 34)
                            .addComponent(jLabel3)
                            .addGap(54, 54, 54)
                            .addComponent(categoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(34, 34, 34)
                            .addComponent(jLabel4))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(49, 49, 49)
                            .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(1090, Short.MAX_VALUE)
                .addComponent(btnProceed, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 292, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(lblname)))
                    .addGap(7, 7, 7)
                    .addComponent(lblcountry)
                    .addGap(22, 22, 22)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(categoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(18, 18, 18)
                    .addComponent(jLabel4)
                    .addGap(28, 28, 28)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(26, 26, 26)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 399, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void categoryComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryComboBoxActionPerformed
        // TODO add your handling code here:

        Category category = (Category) categoryComboBox.getSelectedItem();
        if (category != null){
            populateTblLoanCases(category.getValue());
        }

        // Get the selected category from combo box
        // Call populateTblLoanCases method with this category
    }//GEN-LAST:event_categoryComboBoxActionPerformed

    public void populateAvailableCredit(){
        txtCurrentBalance.setText(String.valueOf(lender.getAccountManagement().getAvailableCredit()));
    }
    
        public void populateOutstanding() {
        
    }

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:

        DefaultTableModel model = (DefaultTableModel) tblLoanCases.getModel();
        int selectedRow = tblLoanCases.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row first","Information",  JOptionPane.INFORMATION_MESSAGE);
            return ;
        }
        else
        {
            Loan loan = (Loan)tblLoanCases.getValueAt(selectedRow, 0);

            for(LendingInstance lendingInstance : loan.getLendingInstanceList() ){
                if(lendingInstance.getLender() == lender){
                    JOptionPane.showMessageDialog(null, "You have already lent to this borrower", "Information", JOptionPane.INFORMATION_MESSAGE);
                    return ;
                }
            }

            MoneyBasket basket = lender.getCurrentBasket();
            for(LendingInstance lendingInstance : basket.getLendingInstanceList()){
                if(loan.getLoanCase() == lendingInstance.getLoanCase()){
                    JOptionPane.showMessageDialog(null, "This loan case is already added to your basket", "Information", JOptionPane.INFORMATION_MESSAGE);
                    return ;
                }
            }
            LendingInstance lendingInstance = new LendingInstance();
            lendingInstance.setLender(lender);
            lendingInstance.setLoanCase(loan.getLoanCase());
            basket.getLendingInstanceList().add(lendingInstance);
            JOptionPane.showMessageDialog(null,  "Item added successfully","Information", JOptionPane.INFORMATION_MESSAGE);
        }

        //Get the selected row loan case
        //Check if lending amount has been inserted
        // Create a lending instance
        // Add this lending instance to loan
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:

        DefaultTableModel model = (DefaultTableModel) tblLoanCases.getModel();
        int selectedRow = tblLoanCases.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null,  "Please select a row first","Information", JOptionPane.INFORMATION_MESSAGE);
            return ;
        }
        else
        {
            int selectedTableRow = tblLoanCases.getSelectedRow();

            if(selectedTableRow >= 0)
            {
                Loan loan = (Loan)tblLoanCases.getValueAt(selectedTableRow, 0);
                ViewBorrowerLoanCaseJPanel viewBorrowerLoanCase = new ViewBorrowerLoanCaseJPanel(userProcessContainer, loan);
                userProcessContainer.add("ViewBorrowerLoanCaseJPanel",viewBorrowerLoanCase);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);

            }

        }

        // Get the selected row and the loan case
        // pass the loan case to new jpanel viewborrowerloancasejpanel
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnProceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProceedActionPerformed
        // TODO add your handling code here:

        MoneyBasketJPanel basketJPanel = new MoneyBasketJPanel(userProcessContainer, business, lender);
        userProcessContainer.add("BasketJPanel",basketJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

        // Create a basket object
        // Add all lending instances to basket object
        // Create a go to basketjpanel with parameter basket
    }//GEN-LAST:event_btnProceedActionPerformed

    private void btnAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd1ActionPerformed
        // TODO add your handling code here:

        DefaultTableModel model = (DefaultTableModel) tblLoanCases.getModel();
        int selectedRow = tblLoanCases.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row first","Information",  JOptionPane.INFORMATION_MESSAGE);
            return ;
        }
        else
        {
            Loan loan = (Loan)tblLoanCases.getValueAt(selectedRow, 0);

            for(LendingInstance lendingInstance : loan.getLendingInstanceList() ){
                if(lendingInstance.getLender() == lender){
                    JOptionPane.showMessageDialog(null, "You have already lent to this borrower", "Information", JOptionPane.INFORMATION_MESSAGE);
                    return ;
                }
            }

            MoneyBasket basket = lender.getCurrentBasket();
            for(LendingInstance lendingInstance : basket.getLendingInstanceList()){
                if(loan.getLoanCase() == lendingInstance.getLoanCase()){
                    JOptionPane.showMessageDialog(null, "This loan case is already added to your basket", "Information", JOptionPane.INFORMATION_MESSAGE);
                    return ;
                }
            }
            LendingInstance lendingInstance = new LendingInstance();
            lendingInstance.setLender(lender);
            lendingInstance.setLoanCase(loan.getLoanCase());
            basket.getLendingInstanceList().add(lendingInstance);
            JOptionPane.showMessageDialog(null,  "Item added successfully","Information", JOptionPane.INFORMATION_MESSAGE);
        }

        //Get the selected row loan case
        //Check if lending amount has been inserted
        // Create a lending instance
        // Add this lending instance to loan
    }//GEN-LAST:event_btnAdd1ActionPerformed

    private void btnView1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnView1ActionPerformed
        // TODO add your handling code here:

        DefaultTableModel model = (DefaultTableModel) tblLoanCases.getModel();
        int selectedRow = tblLoanCases.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null,  "Please select a row first","Information", JOptionPane.INFORMATION_MESSAGE);
            return ;
        }
        else
        {
            int selectedTableRow = tblLoanCases.getSelectedRow();

            if(selectedTableRow >= 0)
            {
                Loan loan = (Loan)tblLoanCases.getValueAt(selectedTableRow, 0);
                ViewBorrowerLoanCaseJPanel viewBorrowerLoanCase = new ViewBorrowerLoanCaseJPanel(userProcessContainer, loan);
                userProcessContainer.add("ViewBorrowerLoanCaseJPanel",viewBorrowerLoanCase);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);

            }

        }

        // Get the selected row and the loan case
        // pass the loan case to new jpanel viewborrowerloancasejpanel
    }//GEN-LAST:event_btnView1ActionPerformed

    private void btnProceed1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProceed1ActionPerformed
        // TODO add your handling code here:

        MoneyBasketJPanel basketJPanel = new MoneyBasketJPanel(userProcessContainer, business, lender);
        userProcessContainer.add("BasketJPanel",basketJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

        // Create a basket object
        // Add all lending instances to basket object
        // Create a go to basketjpanel with parameter basket
    }//GEN-LAST:event_btnProceed1ActionPerformed

    private void categoryComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryComboBox1ActionPerformed
        // TODO add your handling code here:

        Category category = (Category) categoryComboBox.getSelectedItem();
        if (category != null){
            populateTblLoanCases(category.getValue());
        }

        // Get the selected category from combo box
        // Call populateTblLoanCases method with this category
    }//GEN-LAST:event_categoryComboBox1ActionPerformed

    private void btnAddCreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCreditActionPerformed
        // TODO add your handling code here:
        int amount = (int) creditComboBox.getSelectedItem();
        lender.getAccountManagement().setAvailableCredit(lender.getAccountManagement().getAvailableCredit() + amount);
        JOptionPane.showMessageDialog(null,  "Credit added successfully","Information", JOptionPane.INFORMATION_MESSAGE);
        populateAvailableCredit();
    }//GEN-LAST:event_btnAddCreditActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAdd1;
    private javax.swing.JButton btnAddCredit;
    private javax.swing.JButton btnProceed;
    private javax.swing.JButton btnProceed1;
    private javax.swing.JButton btnView;
    private javax.swing.JButton btnView1;
    private javax.swing.JComboBox categoryComboBox;
    private javax.swing.JComboBox categoryComboBox1;
    private javax.swing.JComboBox creditComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblcountry;
    private javax.swing.JLabel lblcountry1;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblname1;
    private javax.swing.JTable tblLoanCases;
    private javax.swing.JTable tblLoanCases1;
    private javax.swing.JTextField txtCurrentBalance;
    private javax.swing.JTextField txtOutstanding;
    // End of variables declaration//GEN-END:variables
}
