/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdministrativeRole;

import Business.Enterprise.Enterprise;
import Business.Organization.FieldPartnerOrganization;
import Business.Organization.Organization;
import Business.WorkQueue.NewFieldPartnerWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shwetatatiya
 */
public class AssignContactToFieldPartnerJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Enterprise enterprise;
    /**
     * Creates new form AssignContactToFieldPartnerJPanel
     */
    public AssignContactToFieldPartnerJPanel(JPanel userProcessContainer, Enterprise enterprise) {
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;        
        initComponents();
        populatetblWorkRequests();
    }

    
    public void populatetblWorkRequests(){
        DefaultTableModel model = (DefaultTableModel) tblWorkRequests.getModel() ;
        model.setRowCount(0);
        
        Object[] row = new Object[4] ;
        for(WorkRequest workRequest : enterprise.getWorkQueue().getWorkRequestList()){
            NewFieldPartnerWorkRequest newFPWR = (NewFieldPartnerWorkRequest) workRequest ;
            
            row[0] = newFPWR ;
            row[1] = newFPWR.getTrustee().getName();
            row[2] = newFPWR.getStatus() ;
            row[3] = newFPWR.getMessage();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblWorkRequests = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnAssignFP = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblWorkRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "OrgName", "Trustee", "Status", "Message"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblWorkRequests);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 565, 211));

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<< BACK");
        btnBack.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 335, 243, 51));

        btnAssignFP.setBackground(new java.awt.Color(0, 0, 0));
        btnAssignFP.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnAssignFP.setForeground(new java.awt.Color(255, 255, 255));
        btnAssignFP.setText("CREATE FIELD PARTNER >>");
        btnAssignFP.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 6, true));
        btnAssignFP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignFPActionPerformed(evt);
            }
        });
        add(btnAssignFP, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 337, 304, 51));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAssignFPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignFPActionPerformed
        // TODO add your handling code here:

        int selectedRow = tblWorkRequests.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(this,  "Please select a row","Information", JOptionPane.INFORMATION_MESSAGE);
            return ;
        }
        DefaultTableModel model = (DefaultTableModel) tblWorkRequests.getModel();
        WorkRequest workRequest = (WorkRequest)model.getValueAt(selectedRow, 0);
        NewFieldPartnerWorkRequest NewFPWR = (NewFieldPartnerWorkRequest) workRequest ;
        FieldPartnerOrganization fieldPartnerOrg = (FieldPartnerOrganization) enterprise.getOrganizationDirectory().createOrganization(Organization.Type.FieldPartner) ;
        fieldPartnerOrg.setGeneralInformation(NewFPWR.getGeneralInformation());
        fieldPartnerOrg.setPerformanceInformation(NewFPWR.getPerformanceInformation());
        fieldPartnerOrg.createAccountManagement();
        fieldPartnerOrg.getPersonDirectory().getPersonList().add(NewFPWR.getFieldPartnerContact()) ;
        NewFPWR.setStatus(NewFieldPartnerWorkRequest.Status.Complete);

        this.populatetblWorkRequests();
        JOptionPane.showMessageDialog(null, "Field Partner created", "Information", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnAssignFPActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignFP;
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblWorkRequests;
    // End of variables declaration//GEN-END:variables
}
