/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */



import javax.swing.JPanel;


/**
 *
 * @author shwetatatiya
 */
public class ManageOrganizationJPanel extends javax.swing.JPanel {

  
    
    /**
     * Creates new form ManageOrganizationJPanel
     */
    public ManageOrganizationJPanel() {
        initComponents();
      
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
