/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.RepresentativeRole;

import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.FieldPartner.GeneralInformation;
import Business.FieldPartner.PerformanceInformation;
import Business.Organization.TrusteeOrganization;
import Business.Person.FieldPartnerContact;
import Business.WorkQueue.NewFieldPartnerWorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Shrutik
 */
public class AnalyseFieldPartnerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AnalyseFieldPartnerJPanel
     */
    
    private JPanel userProcessContainer ;
    private NewFieldPartnerWorkRequest newFieldPartnerWorkRequest ;
    private TrusteeOrganization trusteeOrganization ;
    private Employee representative ; 
    
    public AnalyseFieldPartnerJPanel(JPanel userProcessContainer, NewFieldPartnerWorkRequest newFieldPartnerWorkRequest, 
                                     TrusteeOrganization trusteeOrganization, Employee representative) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.newFieldPartnerWorkRequest = newFieldPartnerWorkRequest ;
        this.trusteeOrganization = trusteeOrganization ;
        this.representative = representative ;
        populateScreenFields();
    }

    
    public void populateScreenFields(){
        
        GeneralInformation generalDetails = newFieldPartnerWorkRequest.getGeneralInformation();
        FieldPartnerContact fieldPartnerContact = newFieldPartnerWorkRequest.getFieldPartnerContact();
        PerformanceInformation performanceDetails = newFieldPartnerWorkRequest.getPerformanceInformation();
        
    lblAddress.setText(generalDetails.getAddress());
    lblCountryOfOperation.setText(generalDetails.getCountryOfOperation());
    lblEmail.setText(fieldPartnerContact.getEmail());
    lblImpactArea.setText(generalDetails.getImpactArea());
    lblJobTitle.setText(fieldPartnerContact.getJobTitle());
    lblLegalStatus.setText(generalDetails.getLegalStatus());
    lblMission.setText(generalDetails.getMissionStatement());
    lblName.setText(fieldPartnerContact.getName());
    lblOrgName.setText(generalDetails.getOrgName());
    lblPhone.setText(fieldPartnerContact.getPhone());
    lblWebsite.setText(generalDetails.getWebsite());        
        
    }   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLegalStatus = new javax.swing.JLabel();
        lblImpactArea = new javax.swing.JLabel();
        txtRiskRating = new javax.swing.JTextField();
        jButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblOrgName = new javax.swing.JLabel();
        lblWebsite = new javax.swing.JLabel();
        lblCountryOfOperation = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblJobTitle = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        lblMission = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        btnSendToTrustee = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 0, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLegalStatus.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblLegalStatus.setForeground(new java.awt.Color(255, 255, 255));
        lblLegalStatus.setText("jLabel2");
        add(lblLegalStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 710, 461, 22));

        lblImpactArea.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblImpactArea.setForeground(new java.awt.Color(255, 255, 255));
        lblImpactArea.setText("jLabel2");
        add(lblImpactArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 750, 469, 22));

        txtRiskRating.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        txtRiskRating.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        add(txtRiskRating, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 800, 151, -1));

        jButton.setBackground(new java.awt.Color(153, 153, 153));
        jButton.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jButton.setForeground(new java.awt.Color(51, 0, 51));
        jButton.setText(" << BACK ");
        jButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 6, true));
        jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActionPerformed(evt);
            }
        });
        add(jButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 890, 160, 63));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" ORGANIZATION NAME ");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 167, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel11.setText("NAME ");
        jLabel11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(709, 167, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(" ORGANIZATION WEBSITE ");
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 215, -1, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText(" JOB TITLE ");
        jLabel12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(711, 213, -1, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText(" PRIMARY COUNTRY OF OPERATION ");
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 277, -1, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText(" EMAIL ");
        jLabel13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(711, 277, -1, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(" HEADQUARTERS ADDRESS ");
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 334, -1, -1));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("PHONE ");
        jLabel14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(713, 336, -1, -1));

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("MISSION STATEMENT");
        jLabel15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, -1));

        lblOrgName.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblOrgName.setForeground(new java.awt.Color(255, 255, 255));
        lblOrgName.setText("jLabel2");
        add(lblOrgName, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 178, 348, 22));

        lblWebsite.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblWebsite.setForeground(new java.awt.Color(255, 255, 255));
        lblWebsite.setText("jLabel2");
        add(lblWebsite, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 215, 332, 22));

        lblCountryOfOperation.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblCountryOfOperation.setForeground(new java.awt.Color(255, 255, 255));
        lblCountryOfOperation.setText("jLabel2");
        add(lblCountryOfOperation, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 280, 261, 22));

        lblAddress.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblAddress.setText("jLabel2");
        add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 385, 512, 22));

        lblName.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("jLabel2");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(878, 170, 248, 22));

        lblJobTitle.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblJobTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblJobTitle.setText("jLabel2");
        add(lblJobTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(878, 216, 248, 22));

        lblEmail.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("jLabel2");
        add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(878, 280, 248, 22));

        lblPhone.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblPhone.setForeground(new java.awt.Color(255, 255, 255));
        lblPhone.setText("jLabel2");
        add(lblPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(878, 339, 248, 22));

        jLabel27.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText(" GENERAL INFORMATION - ");
        jLabel27.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 104, -1, -1));

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("CONTACT INFORMATION -");
        jLabel28.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(709, 108, -1, -1));

        lblMission.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblMission.setForeground(new java.awt.Color(255, 255, 255));
        lblMission.setText("jLabel2");
        add(lblMission, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 512, 22));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ORGANIZATIONAL INFORMATION - ");
        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 640, -1, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("LEGAL STATUS");
        jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 700, -1, -1));

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("IMPACT AREA ");
        jLabel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 750, -1, -1));

        jLabel29.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("RISK RATING ");
        jLabel29.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 800, -1, -1));

        btnSendToTrustee.setBackground(new java.awt.Color(153, 153, 153));
        btnSendToTrustee.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnSendToTrustee.setForeground(new java.awt.Color(51, 0, 51));
        btnSendToTrustee.setText(" SEND TO TRUSTEE ORGANIZATION >> ");
        btnSendToTrustee.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 6, true));
        btnSendToTrustee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendToTrusteeActionPerformed(evt);
            }
        });
        add(btnSendToTrustee, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 890, 405, 63));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ANALYSE FIELD PARTNER");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        int length = userProcessContainer.getComponentCount();
        RepresentativeWorkAreaJPanel rwajp = (RepresentativeWorkAreaJPanel) userProcessContainer.getComponent(length-1);
        rwajp.populateTblRepresentativeOrganizationWorkQueue();

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButtonActionPerformed

    private void btnSendToTrusteeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendToTrusteeActionPerformed
        // TODO add your handling code here:
        String riskRating = txtRiskRating.getText();
        if(riskRating == ""){
            JOptionPane.showMessageDialog(null, "Please enter a risk rating for this Field Partner","Information",  JOptionPane.INFORMATION_MESSAGE);
            return ;
        }
        if(!Enterprise.containsOnlyDigits(riskRating)){
            JOptionPane.showMessageDialog(null,  "Please enter only digits for risk rating","Information", JOptionPane.INFORMATION_MESSAGE);
            return ;
        }
        PerformanceInformation performanceDetails = newFieldPartnerWorkRequest.getPerformanceInformation();
        performanceDetails.setRiskRating(riskRating);

        newFieldPartnerWorkRequest.setRepresentative(representative);
        newFieldPartnerWorkRequest.setMessage("Please review this aplication for new Field Partner");
        newFieldPartnerWorkRequest.setStatus(NewFieldPartnerWorkRequest.Status.RepresentativeRated);
        trusteeOrganization.getWorkQueue().addWorkRequest(newFieldPartnerWorkRequest);

        JOptionPane.showMessageDialog(null,  "Work Request sent to Trustee Organization","Information", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnSendToTrusteeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSendToTrustee;
    private javax.swing.JButton jButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblCountryOfOperation;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblImpactArea;
    private javax.swing.JLabel lblJobTitle;
    private javax.swing.JLabel lblLegalStatus;
    private javax.swing.JLabel lblMission;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblOrgName;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblWebsite;
    private javax.swing.JTextField txtRiskRating;
    // End of variables declaration//GEN-END:variables
}
