/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.RepresentativeRole;

import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.FieldPartner.GeneralInformation;
import Business.FieldPartner.PerformanceInformation;
import Business.Organization.FieldPartnerOrganization;
import Business.Organization.TrusteeOrganization;
import Business.Person.FieldPartnerContact;
import Business.WorkQueue.NewFieldPartnerWorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author Shrutik
 */
public class ViewFieldPartnerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewFieldPartner
     */
    
    private JPanel userProcessContainer ;
    private FieldPartnerOrganization fpo;
    private FieldPartnerContact fpc;
    
    public ViewFieldPartnerJPanel(JPanel userProcessContainer, FieldPartnerOrganization fieldPartnerOrg, FieldPartnerContact fpc) {
        initComponents();
        this.userProcessContainer = userProcessContainer ;
        this.fpo = fieldPartnerOrg;
        this.fpc = fpc;
        populateScreenData();
    }

    public void populateScreenData(){
    lblAddress.setText(fpo.getGeneralInformation().getAddress());
    lblCountryOfOperation.setText(fpo.getGeneralInformation().getCountryOfOperation());
    lblEmail.setText(fpc.getEmail());
    lblLegalStatus.setText(fpo.getGeneralInformation().getLegalStatus());
    lblMission.setText(fpo.getGeneralInformation().getMissionStatement());
    lblName.setText(fpc.getName());
    lblOrgName.setText(fpo.getGeneralInformation().getOrgName());
    lblPhone.setText(fpc.getPhone());
   
   
    lblRiskRating.setText(fpo.getPerformanceInformation().getRiskRating());
    lblTitle.setText(fpc.getJobTitle());
    lblWebsite.setText(fpo.getGeneralInformation().getWebsite());        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel27 = new javax.swing.JLabel();
        lblOrgName = new javax.swing.JLabel();
        lblWebsite = new javax.swing.JLabel();
        lblCountryOfOperation = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        lblMission = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lblLegalStatus = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lblRiskRating = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 0, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText(" GENERAL INFORMATION - ");
        jLabel27.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        lblOrgName.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblOrgName.setForeground(new java.awt.Color(255, 255, 255));
        lblOrgName.setText("jLabel2");
        add(lblOrgName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 348, 22));

        lblWebsite.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblWebsite.setForeground(new java.awt.Color(255, 255, 255));
        lblWebsite.setText("jLabel2");
        add(lblWebsite, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 332, 22));

        lblCountryOfOperation.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblCountryOfOperation.setForeground(new java.awt.Color(255, 255, 255));
        lblCountryOfOperation.setText("jLabel2");
        add(lblCountryOfOperation, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 261, 22));

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText(" ORGANIZATION NAME ");
        jLabel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel16.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText(" ORGANIZATION WEBSITE ");
        jLabel16.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        lblAddress.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblAddress.setText("jLabel2");
        add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 190, 22));

        jLabel17.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText(" PRIMARY COUNTRY OF OPERATION ");
        jLabel17.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        jLabel18.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText(" HEADQUARTERS ADDRESS ");
        jLabel18.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        jLabel30.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("CONTACT INFORMATION -");
        jLabel30.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 110, -1, 40));

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel24.setText("NAME ");
        jLabel24.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 200, 116, -1));

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText(" JOB TITLE ");
        jLabel25.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 240, -1, -1));

        jLabel31.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText(" EMAIL ");
        jLabel31.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 280, -1, -1));

        jLabel32.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("PHONE ");
        jLabel32.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 330, -1, -1));

        lblMission.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblMission.setForeground(new java.awt.Color(255, 255, 255));
        lblMission.setText("jLabel2");
        add(lblMission, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, 512, 22));

        jLabel19.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("MISSION STATEMENT");
        jLabel19.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

        lblLegalStatus.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblLegalStatus.setForeground(new java.awt.Color(255, 255, 255));
        lblLegalStatus.setText("jLabel2");
        add(lblLegalStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 540, 952, 22));

        jLabel21.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("LEGAL STATUS");
        jLabel21.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, -1, -1));

        lblRiskRating.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblRiskRating.setForeground(new java.awt.Color(255, 255, 255));
        lblRiskRating.setText("jLabel2");
        add(lblRiskRating, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 620, 990, 22));

        btnBack.setBackground(new java.awt.Color(153, 153, 153));
        btnBack.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(51, 0, 51));
        btnBack.setText("<< BACK");
        btnBack.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 720, 210, 62));

        jLabel29.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("RISK RATING ");
        jLabel29.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, -1, -1));

        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("jLabel2");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 200, 248, 22));

        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("jLabel2");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 240, 248, 22));

        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("jLabel2");
        add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 290, 248, 22));

        lblPhone.setForeground(new java.awt.Color(255, 255, 255));
        lblPhone.setText("jLabel2");
        add(lblPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 340, 248, 22));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("VIEW FIELD PARTNER");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        int length = userProcessContainer.getComponentCount();
        RepresentativeLoanCaseJPanel rlcjp = (RepresentativeLoanCaseJPanel) userProcessContainer.getComponent(length-1);
        rlcjp.populateScreenData();

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblCountryOfOperation;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblLegalStatus;
    private javax.swing.JLabel lblMission;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblOrgName;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblRiskRating;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWebsite;
    // End of variables declaration//GEN-END:variables
}
