/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.TrusteeRole;

import Business.Enterprise.HelpingHandsEnterprise;
import Business.FieldPartner.GeneralInformation;
import Business.FieldPartner.PerformanceInformation;
import Business.Person.FieldPartnerContact;
import Business.WorkQueue.NewFieldPartnerWorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Shrutik
 */
public class TrusteeViewFieldPartnerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TrusteeViewFieldPartnerJPanel
     */
    
    private JPanel userProcessContainer ;
    private HelpingHandsEnterprise business ;
    private NewFieldPartnerWorkRequest nfpwr;
    
    public TrusteeViewFieldPartnerJPanel(JPanel userProcessContainer, HelpingHandsEnterprise business,NewFieldPartnerWorkRequest nfpwr) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.nfpwr = nfpwr;
        
        populateData();
    }

     public void populateData()
    {
        GeneralInformation gd = nfpwr.getGeneralInformation();
        PerformanceInformation pd = nfpwr.getPerformanceInformation();
        FieldPartnerContact fpc = nfpwr.getFieldPartnerContact();
        
        lblOrgName.setText(gd.getOrgName());
        lblWebsite.setText(gd.getWebsite());
        lblCountryOfOperation.setText(gd.getCountryOfOperation());
        lblAddress.setText(gd.getAddress());
        lblMission.setText(gd.getMissionStatement());
        lblLegalStatus.setText(gd.getLegalStatus());
        lblImpactArea.setText(gd.getImpactArea());
        
        if(gd.getRefPerson() != null)
        lblRefPerson.setText(gd.getRefPerson().getName());
        
        lblName.setText(fpc.getName());
        lblPhone.setText(fpc.getPhone());
        lblEmail.setText(fpc.getEmail());
        lblTitle.setText(fpc.getJobTitle());
        
        lblRiskRating.setText(pd.getRiskRating());
        
   
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel27 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lblOrgName = new javax.swing.JLabel();
        lblWebsite = new javax.swing.JLabel();
        lblCountryOfOperation = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lblMission = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        lblRiskRating = new javax.swing.JLabel();
        lblRefPerson = new javax.swing.JLabel();
        lblImpactArea = new javax.swing.JLabel();
        lblLegalStatus = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnApprove = new javax.swing.JButton();
        btnReject = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("  GENERAL INFORMATION -  ");
        jLabel27.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 64, -1, -1));

        jLabel16.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText(" ORGANIZATION WEBSITE ");
        jLabel16.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 162, -1, -1));

        jLabel17.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText(" PRIMARY COUNTRY OF OPERATION ");
        jLabel17.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 203, -1, -1));

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText(" ORGANIZATION NAME ");
        jLabel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 251, -1, -1));

        jLabel18.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText(" HEADQUARTERS ADDRESS ");
        jLabel18.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 299, -1, -1));

        lblOrgName.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblOrgName.setForeground(new java.awt.Color(255, 255, 255));
        lblOrgName.setText("jLabel2");
        add(lblOrgName, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 162, 348, 22));

        lblWebsite.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblWebsite.setForeground(new java.awt.Color(255, 255, 255));
        lblWebsite.setText("jLabel2");
        add(lblWebsite, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 203, 332, 22));

        lblCountryOfOperation.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblCountryOfOperation.setForeground(new java.awt.Color(255, 255, 255));
        lblCountryOfOperation.setText("jLabel2");
        add(lblCountryOfOperation, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 255, 261, 22));

        lblAddress.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblAddress.setText("jLabel2");
        add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 392, 512, 22));

        jLabel19.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("MISSION STATEMENT");
        jLabel19.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 533, -1, -1));

        lblMission.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblMission.setForeground(new java.awt.Color(255, 255, 255));
        lblMission.setText("jLabel2");
        add(lblMission, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 581, 512, 22));

        jLabel20.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("ORGANIZATIONAL INFORMATION - ");
        jLabel20.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 615, -1, -1));

        jLabel22.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("IMPACT AREA ");
        jLabel22.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 720, -1, -1));

        jLabel21.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("LEGAL STATUS");
        jLabel21.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 680, -1, -1));

        jLabel23.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("HELPING HANDS REFERENCE PERSON (IF ANY) ");
        jLabel23.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 770, -1, -1));

        jLabel29.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("RISK RATING ");
        jLabel29.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 832, -1, -1));

        lblRiskRating.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblRiskRating.setForeground(new java.awt.Color(255, 255, 255));
        lblRiskRating.setText("jLabel2");
        add(lblRiskRating, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 832, 738, 22));

        lblRefPerson.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblRefPerson.setForeground(new java.awt.Color(255, 255, 255));
        lblRefPerson.setText("jLabel2");
        add(lblRefPerson, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 770, 738, 22));

        lblImpactArea.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblImpactArea.setForeground(new java.awt.Color(255, 255, 255));
        lblImpactArea.setText("jLabel2");
        add(lblImpactArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 711, 738, 22));

        lblLegalStatus.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblLegalStatus.setForeground(new java.awt.Color(255, 255, 255));
        lblLegalStatus.setText("jLabel2");
        add(lblLegalStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 671, 326, 22));

        jLabel32.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("PHONE ");
        jLabel32.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(719, 441, -1, -1));

        lblPhone.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblPhone.setForeground(new java.awt.Color(255, 255, 255));
        lblPhone.setText("jLabel2");
        add(lblPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(883, 443, 248, 22));

        jLabel31.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText(" EMAIL ");
        jLabel31.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(717, 380, -1, -1));

        lblEmail.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("jLabel2");
        add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(883, 382, 248, 22));

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText(" JOB TITLE ");
        jLabel25.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(717, 320, -1, -1));

        lblName.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("jLabel2");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(883, 322, 248, 22));

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel11.setText("  NAME  ");
        jLabel11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(717, 190, 108, -1));

        jLabel30.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("CONTACT INFORMATION -");
        jLabel30.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 140, -1, -1));

        lblTitle.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("jLabel2");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(883, 186, 248, 22));

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<< BACK  ");
        btnBack.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 932, 186, 70));

        btnApprove.setBackground(new java.awt.Color(0, 0, 0));
        btnApprove.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        btnApprove.setForeground(new java.awt.Color(255, 255, 255));
        btnApprove.setText("APPROVE >>");
        btnApprove.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        btnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveActionPerformed(evt);
            }
        });
        add(btnApprove, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 932, 221, 70));

        btnReject.setBackground(new java.awt.Color(0, 0, 0));
        btnReject.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        btnReject.setForeground(new java.awt.Color(255, 255, 255));
        btnReject.setText("REJECT >>");
        btnReject.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });
        add(btnReject, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 932, 244, 70));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        int length = userProcessContainer.getComponentCount();
        TrusteeWorkAreaJPanel twajp = (TrusteeWorkAreaJPanel) userProcessContainer.getComponent(length-1);
        twajp.populateBorrowerWorkTable();
        twajp.populateFieldPartnerWorkTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveActionPerformed
        // TODO add your handling code here:

        nfpwr.setStatus(NewFieldPartnerWorkRequest.Status.TrusteeApproved);
        nfpwr.setMessage("Please Create The New Field Partner Account");
        business.getWorkQueue().addWorkRequest(nfpwr);

        JOptionPane.showMessageDialog(null,  "The given Field Partner is Approved","Information", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnApproveActionPerformed

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed
        // TODO add your handling code here:

        nfpwr.setStatus(NewFieldPartnerWorkRequest.Status.TrusteeRejected);
        nfpwr.setMessage("The given Field Partner does not meet the criteria, thus the given Partner is REJECTED");
        JOptionPane.showMessageDialog(null,  "the given Field Partner is Rejected","Information", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnRejectActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnReject;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblCountryOfOperation;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblImpactArea;
    private javax.swing.JLabel lblLegalStatus;
    private javax.swing.JLabel lblMission;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblOrgName;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblRefPerson;
    private javax.swing.JLabel lblRiskRating;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWebsite;
    // End of variables declaration//GEN-END:variables
}
