/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.TrusteeRole;



import Business.Enterprise.HelpingHandsEnterprise;
import Business.FieldPartner.GeneralInformation;
import Business.Person.FieldPartnerContact;
import Business.WorkQueue.NewFieldPartnerWorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Shrutik
 */
public class TrusteeViewFieldPartnerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TrusteeViewFieldPartnerJPanel
     */
    private JPanel userProcessContainer ;
    private HelpingHandsEnterprise business ;
    private NewFieldPartnerWorkRequest nfpwr;
    
    
    public TrusteeViewFieldPartnerJPanel(JPanel userProcessContainer, HelpingHandsEnterprise business,NewFieldPartnerWorkRequest nfpwr) 
    {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.nfpwr = nfpwr;
        
        populateData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void populateData()
    {
        GeneralInformation gd = nfpwr.getGeneralInformation();
        Business.FieldPartner.PerformanceInformation pd = nfpwr.getPerformanceInformation();
        FieldPartnerContact fpc = nfpwr.getFieldPartnerContact();
        
        lblOrgName.setText(gd.getOrgName());
        lblWebsite.setText(gd.getWebsite());
        lblCountryOfOperation.setText(gd.getCountryOfOperation());
        lblAddress.setText(gd.getAddress());
        lblMission.setText(gd.getMissionStatement());
        lblLegalStatus.setText(gd.getLegalStatus());
        
        lblName.setText(fpc.getName());
        lblPhone.setText(fpc.getPhone());
        lblEmail.setText(fpc.getEmail());
        lblTitle.setText(fpc.getJobTitle());
        
        lblRiskRating.setText(pd.getRiskRating());
        
   
        
                
        
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        lblOrgName = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblWebsite = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblCountryOfOperation = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblMission = new javax.swing.JLabel();
        lblLegalStatus = new javax.swing.JLabel();
        lblRiskRating = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnApprove = new javax.swing.JButton();
        btnReject = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("  GENERAL INFORMATION -  ");
        jLabel27.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        lblOrgName.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblOrgName.setForeground(new java.awt.Color(255, 255, 255));
        lblOrgName.setText("jLabel2");
        jPanel1.add(lblOrgName, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 348, -1));

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel11.setText("  NAME  ");
        jLabel11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 160, 108, -1));

        lblName.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("jLabel2");
        jPanel1.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 160, 248, -1));

        lblWebsite.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblWebsite.setForeground(new java.awt.Color(255, 255, 255));
        lblWebsite.setText("jLabel2");
        jPanel1.add(lblWebsite, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 332, -1));

        lblTitle.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("jLabel2");
        jPanel1.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 220, 248, -1));

        lblCountryOfOperation.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblCountryOfOperation.setForeground(new java.awt.Color(255, 255, 255));
        lblCountryOfOperation.setText("jLabel2");
        jPanel1.add(lblCountryOfOperation, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 261, -1));

        lblEmail.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("jLabel2");
        jPanel1.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 280, 248, -1));

        lblPhone.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblPhone.setForeground(new java.awt.Color(255, 255, 255));
        lblPhone.setText("jLabel2");
        jPanel1.add(lblPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 340, 248, -1));

        lblAddress.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblAddress.setText("jLabel2");
        jPanel1.add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 512, -1));

        lblMission.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblMission.setForeground(new java.awt.Color(255, 255, 255));
        lblMission.setText("jLabel2");
        jPanel1.add(lblMission, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 512, -1));

        lblLegalStatus.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblLegalStatus.setForeground(new java.awt.Color(255, 255, 255));
        lblLegalStatus.setText("jLabel2");
        jPanel1.add(lblLegalStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 650, 326, -1));

        lblRiskRating.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblRiskRating.setForeground(new java.awt.Color(255, 255, 255));
        lblRiskRating.setText("jLabel2");
        jPanel1.add(lblRiskRating, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 710, 739, -1));

        btnBack.setBackground(new java.awt.Color(153, 153, 153));
        btnBack.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(51, 0, 51));
        btnBack.setText("<< BACK  ");
        btnBack.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 810, 186, 70));

        btnApprove.setBackground(new java.awt.Color(153, 153, 153));
        btnApprove.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        btnApprove.setForeground(new java.awt.Color(51, 0, 51));
        btnApprove.setText("APPROVE >>");
        btnApprove.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        btnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveActionPerformed(evt);
            }
        });
        jPanel1.add(btnApprove, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 810, 221, 70));

        btnReject.setBackground(new java.awt.Color(153, 153, 153));
        btnReject.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        btnReject.setForeground(new java.awt.Color(51, 0, 51));
        btnReject.setText("REJECT >>");
        btnReject.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });
        jPanel1.add(btnReject, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 810, 240, 70));

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText(" ORGANIZATION NAME ");
        jLabel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jLabel16.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText(" ORGANIZATION WEBSITE ");
        jLabel16.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel17.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText(" PRIMARY COUNTRY OF OPERATION ");
        jLabel17.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel18.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText(" HEADQUARTERS ADDRESS ");
        jLabel18.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        jLabel19.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("MISSION STATEMENT");
        jLabel19.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        jLabel20.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("ORGANIZATIONAL INFORMATION - ");
        jLabel20.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, -1, -1));

        jLabel21.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("LEGAL STATUS");
        jLabel21.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 650, -1, -1));

        jLabel29.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("RISK RATING ");
        jLabel29.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 710, -1, -1));

        jLabel30.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("CONTACT INFORMATION -");
        jLabel30.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 100, -1, -1));

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText(" JOB TITLE ");
        jLabel25.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 220, -1, -1));

        jLabel31.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText(" EMAIL ");
        jLabel31.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 280, -1, -1));

        jLabel32.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("PHONE ");
        jLabel32.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 340, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("VIEW FIELD PARTNER(TRUSTEE)");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1092, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveActionPerformed
        // TODO add your handling code here:

        nfpwr.setStatus(NewFieldPartnerWorkRequest.Status.TrusteeApproved);
        nfpwr.setMessage("Please Create The New Field Partner Account");
        business.getWorkQueue().addWorkRequest(nfpwr);
        
        JOptionPane.showMessageDialog(null,  "The given Field Partner is Approved","Information", JOptionPane.INFORMATION_MESSAGE);
        
        
    }//GEN-LAST:event_btnApproveActionPerformed

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed
        // TODO add your handling code here:
        
        nfpwr.setStatus(NewFieldPartnerWorkRequest.Status.TrusteeRejected);
        nfpwr.setMessage("The give Field Partner does not meets the criteria, thus the give Partner is REJECTED");
        JOptionPane.showMessageDialog(null,  "the given Field Partner is Rejected","Information", JOptionPane.INFORMATION_MESSAGE);
        
        
    }//GEN-LAST:event_btnRejectActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        int length = userProcessContainer.getComponentCount();
        TrusteeWorkAreaJPanel awajp = (TrusteeWorkAreaJPanel) userProcessContainer.getComponent(length-1); 
        awajp.populateBorrowerWorkTable();
        awajp.populateFieldPartnerWorkTable();        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnReject;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblCountryOfOperation;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblLegalStatus;
    private javax.swing.JLabel lblMission;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblOrgName;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblRiskRating;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWebsite;
    // End of variables declaration//GEN-END:variables
}
