/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.TrusteeRole;

import Business.Employee.Employee;
import Business.Enterprise.HelpingHandsEnterprise;
import Business.Organization.TrusteeOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.NewLoanCaseWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shwetatatiya
 */
public class TrusteeWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TrusteeWorkAreaJPanel
     */
    
    private JPanel userProcessContainer ;
    private HelpingHandsEnterprise business ;
    private UserAccount userAccount ;
    private Employee trustee ;
    
    public TrusteeWorkAreaJPanel(JPanel userProcessContainer, HelpingHandsEnterprise helpingHandsEnterprise, UserAccount account, Employee employee) {
        initComponents();
        this.userProcessContainer = userProcessContainer ;
        this.business = helpingHandsEnterprise ;
        this.userAccount = userAccount ;
        this.trustee = trustee ;
        
        populateBorrowerWorkTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBorrowerWorkCase = new javax.swing.JTable();
        btnViewDetails = new javax.swing.JButton();
        btnBorrowerAssignToMe = new javax.swing.JButton();
        btnViewHelpingHandsRevenue = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("  TRUSTEE WORK AREA  ");
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 6, -1, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("  BORROWER WORK CASE  ");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 115, -1, -1));

        tblBorrowerWorkCase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Borrower Name", "Category", "Loan Amount", "Loan Length", "Analyst", "Trustee"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblBorrowerWorkCase);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 188, 667, 128));

        btnViewDetails.setBackground(new java.awt.Color(0, 0, 0));
        btnViewDetails.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnViewDetails.setForeground(new java.awt.Color(255, 255, 255));
        btnViewDetails.setText("VIEW DETAILS >>  ");
        btnViewDetails.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        btnViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsActionPerformed(evt);
            }
        });
        add(btnViewDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 360, 312, 50));

        btnBorrowerAssignToMe.setBackground(new java.awt.Color(0, 0, 0));
        btnBorrowerAssignToMe.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnBorrowerAssignToMe.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrowerAssignToMe.setText("ASSIGN TO ME >>");
        btnBorrowerAssignToMe.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        btnBorrowerAssignToMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrowerAssignToMeActionPerformed(evt);
            }
        });
        add(btnBorrowerAssignToMe, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 360, 337, 50));

        btnViewHelpingHandsRevenue.setBackground(new java.awt.Color(0, 0, 0));
        btnViewHelpingHandsRevenue.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        btnViewHelpingHandsRevenue.setForeground(new java.awt.Color(255, 255, 255));
        btnViewHelpingHandsRevenue.setText("VIEW HELPING HANDS REVENUE COLLECTION >>");
        btnViewHelpingHandsRevenue.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 6, true));
        btnViewHelpingHandsRevenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewHelpingHandsRevenueActionPerformed(evt);
            }
        });
        add(btnViewHelpingHandsRevenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 508, 667, 72));
    }// </editor-fold>//GEN-END:initComponents

    
    public void populateBorrowerWorkTable()
    {
         DefaultTableModel model = (DefaultTableModel) tblBorrowerWorkCase.getModel();
         model.setRowCount(0);
         
         TrusteeOrganization trusteeOrg = business.getTrusteeOrganization();
         
         for(WorkRequest workRequest : trusteeOrg.getWorkQueue().getWorkRequestList())
         {
             if(workRequest instanceof NewLoanCaseWorkRequest)
                
             {NewLoanCaseWorkRequest nlcwr = (NewLoanCaseWorkRequest)workRequest;
                if(!nlcwr.getStatus().equals(NewLoanCaseWorkRequest.Status.Complete.getValue())){                
                   
                
                Object row [] = new Object[6];
                row[0] = nlcwr;
                row[1] = nlcwr.getLoan().getLoanCase().getCategory();
                row[2] = nlcwr.getLoan().getLoanCase().getLoanAmount();
                row[3] = nlcwr.getLoan().getLoanCase().getLoanLength();
                row[4] = nlcwr.getRepresentative().getName();
                if(nlcwr.getTrustee() != null)
                row[5] = nlcwr.getTrustee().getName();
                else
                row[5] = "";    
                model.addRow(row); 
             
                
                
             }}
                
         }
         
         
        
    }
    
    
    
    
    
    private void btnViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsActionPerformed
        // TODO add your handling code here:

        DefaultTableModel model = (DefaultTableModel) tblBorrowerWorkCase.getModel();
        int selectedRow = tblBorrowerWorkCase.getSelectedRow();
        if(selectedRow < 0)
        {
            JOptionPane.showMessageDialog(null, "Please select a row first","Information",  JOptionPane.INFORMATION_MESSAGE);
            return ;
        }
        else
        {
            NewLoanCaseWorkRequest nlcwr = (NewLoanCaseWorkRequest)tblBorrowerWorkCase.getValueAt(selectedRow, 0);
            if(nlcwr.getTrustee() != trustee){
                JOptionPane.showMessageDialog(null, "Please assign to yourself first", "Information", JOptionPane.INFORMATION_MESSAGE);
                return ;
            }

            TrusteeViewLoanCaseJPanel trusteeViewLoanCaseJPanel = new TrusteeViewLoanCaseJPanel(userProcessContainer,business,nlcwr);
            userProcessContainer.add("trusteeViewLoanCaseJPanel",trusteeViewLoanCaseJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }

    }//GEN-LAST:event_btnViewDetailsActionPerformed

    private void btnBorrowerAssignToMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrowerAssignToMeActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblBorrowerWorkCase.getModel();
        int selectedRow = tblBorrowerWorkCase.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null,  "Please select a row first","Information", JOptionPane.INFORMATION_MESSAGE);
            return ;
        }
        else
        {
            NewLoanCaseWorkRequest nlcwr = (NewLoanCaseWorkRequest)tblBorrowerWorkCase.getValueAt(selectedRow, 0);
            // Check if it is already assigned
            if(nlcwr.getTrustee() != null){
                JOptionPane.showMessageDialog(null, "Trustee already assigned", "Information", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            nlcwr.setTrustee(trustee);
        }

        JOptionPane.showMessageDialog(null,"Work request assigned", "Information", JOptionPane.INFORMATION_MESSAGE);
        populateBorrowerWorkTable();
    }//GEN-LAST:event_btnBorrowerAssignToMeActionPerformed

    private void btnViewHelpingHandsRevenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewHelpingHandsRevenueActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnViewHelpingHandsRevenueActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrowerAssignToMe;
    private javax.swing.JButton btnViewDetails;
    private javax.swing.JButton btnViewHelpingHandsRevenue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblBorrowerWorkCase;
    // End of variables declaration//GEN-END:variables
}
