/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.TrusteeRole;


import Business.Employee.Employee;
import Business.Enterprise.HelpingHandsEnterprise;
import Business.Organization.TrusteeOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.NewFieldPartnerWorkRequest;
import Business.WorkQueue.NewLoanCaseWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shwetatatiya
 */
public class TrusteeWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer ;
    private HelpingHandsEnterprise business ;
    private UserAccount userAccount ;
    private Employee trustee ;
    /**
     * Creates new form TrusteeWorkAreaJPanel
     */
    public TrusteeWorkAreaJPanel() {
        initComponents();
    }

    public TrusteeWorkAreaJPanel(JPanel userProcessContainer, HelpingHandsEnterprise enterprise, UserAccount account, Employee trustee) {
        initComponents();
        this.userProcessContainer = userProcessContainer ;
        this.business = enterprise ;
        this.userAccount = userAccount ;
        this.trustee = trustee ;
        
        populateFieldPartnerWorkTable();
        populateBorrowerWorkTable();
        populateFieldPartnerWorkTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void populateBorrowerWorkTable()
    {
         DefaultTableModel model = (DefaultTableModel) tblBorrowerWorkCase.getModel();
         model.setRowCount(0);
         
         TrusteeOrganization trusteeOrg = business.getTrusteeOrganization();
         
         for(WorkRequest workRequest : trusteeOrg.getWorkQueue().getWorkRequestList())
         {
             if(workRequest instanceof NewLoanCaseWorkRequest)
                
             {NewLoanCaseWorkRequest nlcwr = (NewLoanCaseWorkRequest)workRequest;
                if(!nlcwr.getStatus().equals(NewLoanCaseWorkRequest.Status.Complete.getValue())){                
                   
                
                Object row [] = new Object[6];
                row[0] = nlcwr;
                row[1] = nlcwr.getLoan().getLoanCase().getCategory();
                row[2] = nlcwr.getLoan().getLoanCase().getLoanAmount();
                row[3] = nlcwr.getLoan().getLoanCase().getLoanLength();
                row[4] = nlcwr.getRepresentative().getName();
                if(nlcwr.getTrustee() != null)
                row[5] = nlcwr.getTrustee().getName();
                else
                row[5] = "";    
                model.addRow(row); 
             
                
                
             }}
                
         }
         
         
        
    }
    
    public void populateFieldPartnerWorkTable()
    {
        DefaultTableModel model = (DefaultTableModel) tblFieldPartnerWorkCase.getModel();
        model.setRowCount(0);
        
        DefaultTableModel modelina = (DefaultTableModel) tblFieldPartnerWorkCase.getModel();
        model.setRowCount(0);
         
        TrusteeOrganization trusteeOrg = business.getTrusteeOrganization();
         
        for(WorkRequest workRequest : trusteeOrg.getWorkQueue().getWorkRequestList())
        {
            if(workRequest instanceof NewFieldPartnerWorkRequest)
            {
                NewFieldPartnerWorkRequest nfpwr = (NewFieldPartnerWorkRequest)workRequest;                
                if(!nfpwr.getStatus().equals(NewFieldPartnerWorkRequest.Status.Complete.getValue())){
                      
                
               
                Object row [] = new Object[6];
                row[0] = nfpwr;
                row[1] = nfpwr.getRepresentative().getName();
                row[2] = nfpwr.getPerformanceInformation().getRiskRating();
                row[3] = nfpwr.getStatus();
                row[4] = nfpwr.getRepresentative().getName();
                if(nfpwr.getTrustee() != null)
                row[5] = nfpwr.getTrustee().getName();
                else
                row[5] = "";                 
                model.addRow(row); 
             
            }}
                
        }
        
         
         
        
    }
    
    
    
    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBorrowerWorkCase = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblFieldPartnerWorkCase = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnViewDetails = new javax.swing.JButton();
        btnViewFieldPartnerDetails = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnViewRevenue = new javax.swing.JButton();
        btnBorrowerAssignToMe = new javax.swing.JButton();
<<<<<<< HEAD
        btnFieldPartnerAssignToMe = new javax.swing.JButton();
=======
        btnViewHelpingHandsRevenue = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblFieldPartnerWorkCase = new javax.swing.JTable();
        btnViewFieldPartnerDetails = new javax.swing.JButton();
        btnFieldPartnerAssignToMe = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
>>>>>>> 9f88221fa9a78811a4d9781a72be3543a6cb363c

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblBorrowerWorkCase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Borrower Name", "Category", "Loan Amount", "Loan Length", "Representative", "Trustee"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblBorrowerWorkCase);
        if (tblBorrowerWorkCase.getColumnModel().getColumnCount() > 0) {
            tblBorrowerWorkCase.getColumnModel().getColumn(0).setResizable(false);
            tblBorrowerWorkCase.getColumnModel().getColumn(1).setResizable(false);
            tblBorrowerWorkCase.getColumnModel().getColumn(2).setResizable(false);
            tblBorrowerWorkCase.getColumnModel().getColumn(3).setResizable(false);
            tblBorrowerWorkCase.getColumnModel().getColumn(4).setResizable(false);
            tblBorrowerWorkCase.getColumnModel().getColumn(5).setResizable(false);
        }

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 242, 667, 128));

        tblFieldPartnerWorkCase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Organization Name", "Representative Name", "Risk Rating", "Status", "Representative", "Trustee"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblFieldPartnerWorkCase);
        if (tblFieldPartnerWorkCase.getColumnModel().getColumnCount() > 0) {
            tblFieldPartnerWorkCase.getColumnModel().getColumn(0).setResizable(false);
            tblFieldPartnerWorkCase.getColumnModel().getColumn(1).setResizable(false);
            tblFieldPartnerWorkCase.getColumnModel().getColumn(2).setResizable(false);
            tblFieldPartnerWorkCase.getColumnModel().getColumn(3).setResizable(false);
            tblFieldPartnerWorkCase.getColumnModel().getColumn(4).setResizable(false);
            tblFieldPartnerWorkCase.getColumnModel().getColumn(5).setResizable(false);
        }

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 590, 667, 126));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("  BORROWER WORK CASE  ");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 169, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("  FIELD PARTNER WORK CASE  ");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 540, -1, -1));

        btnViewDetails.setBackground(new java.awt.Color(153, 153, 153));
        btnViewDetails.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnViewDetails.setForeground(new java.awt.Color(51, 0, 51));
        btnViewDetails.setText("VIEW DETAILS >>  ");
        btnViewDetails.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        btnViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsActionPerformed(evt);
            }
        });
        jPanel1.add(btnViewDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 414, 312, 50));

        btnViewFieldPartnerDetails.setBackground(new java.awt.Color(153, 153, 153));
        btnViewFieldPartnerDetails.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnViewFieldPartnerDetails.setForeground(new java.awt.Color(51, 0, 51));
        btnViewFieldPartnerDetails.setText("VIEW DETAILS >>");
        btnViewFieldPartnerDetails.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        btnViewFieldPartnerDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewFieldPartnerDetailsActionPerformed(evt);
            }
        });
        jPanel1.add(btnViewFieldPartnerDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 740, 301, 58));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("  TRUSTEE WORK AREA  ");
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 60, -1, -1));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 0, -1, -1));

        btnViewRevenue.setBackground(new java.awt.Color(153, 153, 153));
        btnViewRevenue.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        btnViewRevenue.setForeground(new java.awt.Color(51, 0, 51));
        btnViewRevenue.setText("VIEW HELPING HANDS REVENUE COLLECTION >>");
        btnViewRevenue.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 6, true));
        btnViewRevenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewRevenueActionPerformed(evt);
            }
        });
        jPanel1.add(btnViewRevenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 820, 667, 72));

        btnBorrowerAssignToMe.setBackground(new java.awt.Color(153, 153, 153));
        btnBorrowerAssignToMe.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnBorrowerAssignToMe.setForeground(new java.awt.Color(51, 0, 51));
        btnBorrowerAssignToMe.setText("ASSIGN TO ME >>");
        btnBorrowerAssignToMe.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        btnBorrowerAssignToMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrowerAssignToMeActionPerformed(evt);
            }
        });
<<<<<<< HEAD
        jPanel1.add(btnBorrowerAssignToMe, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 414, 337, 50));

        btnFieldPartnerAssignToMe.setBackground(new java.awt.Color(153, 153, 153));
        btnFieldPartnerAssignToMe.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnFieldPartnerAssignToMe.setForeground(new java.awt.Color(51, 0, 51));
        btnFieldPartnerAssignToMe.setText("ASSIGN TO ME >>");
        btnFieldPartnerAssignToMe.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        btnFieldPartnerAssignToMe.addActionListener(new java.awt.event.ActionListener() {
=======
        add(btnBorrowerAssignToMe, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, 337, 50));

        btnViewHelpingHandsRevenue.setBackground(new java.awt.Color(0, 0, 0));
        btnViewHelpingHandsRevenue.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        btnViewHelpingHandsRevenue.setForeground(new java.awt.Color(255, 255, 255));
        btnViewHelpingHandsRevenue.setText("VIEW HELPING HANDS REVENUE COLLECTION >>");
        btnViewHelpingHandsRevenue.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 6, true));
        btnViewHelpingHandsRevenue.addActionListener(new java.awt.event.ActionListener() {
>>>>>>> 9f88221fa9a78811a4d9781a72be3543a6cb363c
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFieldPartnerAssignToMeActionPerformed(evt);
            }
        });
<<<<<<< HEAD
        jPanel1.add(btnFieldPartnerAssignToMe, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 740, 348, 58));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 983, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1045, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewRevenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewRevenueActionPerformed
=======
        add(btnViewHelpingHandsRevenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 820, 667, 72));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("  FIELD PARTNER WORK CASE  ");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, -1, -1));

        tblFieldPartnerWorkCase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Organization Name", "Analyst Name", "Risk Rating", "Status", "Analyst", "Trustee"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblFieldPartnerWorkCase);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, 667, 126));

        btnViewFieldPartnerDetails.setBackground(new java.awt.Color(0, 0, 0));
        btnViewFieldPartnerDetails.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnViewFieldPartnerDetails.setForeground(new java.awt.Color(255, 255, 255));
        btnViewFieldPartnerDetails.setText("VIEW DETAILS >>");
        btnViewFieldPartnerDetails.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        btnViewFieldPartnerDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewFieldPartnerDetailsActionPerformed(evt);
            }
        });
        add(btnViewFieldPartnerDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 700, 301, 58));

        btnFieldPartnerAssignToMe.setBackground(new java.awt.Color(0, 0, 0));
        btnFieldPartnerAssignToMe.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnFieldPartnerAssignToMe.setForeground(new java.awt.Color(255, 255, 255));
        btnFieldPartnerAssignToMe.setText("ASSIGN TO ME >>");
        btnFieldPartnerAssignToMe.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        btnFieldPartnerAssignToMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFieldPartnerAssignToMeActionPerformed(evt);
            }
        });
        add(btnFieldPartnerAssignToMe, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 700, 348, 58));
    }// </editor-fold>//GEN-END:initComponents

    
    public void populateFieldPartnerWorkTable()
    {
        DefaultTableModel model = (DefaultTableModel) tblFieldPartnerWorkCase.getModel();
        model.setRowCount(0);
        
        DefaultTableModel modelina = (DefaultTableModel) tblFieldPartnerWorkCase.getModel();
        model.setRowCount(0);
         
        TrusteeOrganization trusteeOrg = business.getTrusteeOrganization();
         
        for(WorkRequest workRequest : trusteeOrg.getWorkQueue().getWorkRequestList())
        {
            if(workRequest instanceof NewFieldPartnerWorkRequest)
            {
                NewFieldPartnerWorkRequest nfpwr = (NewFieldPartnerWorkRequest)workRequest;                
                if(!nfpwr.getStatus().equals(NewFieldPartnerWorkRequest.Status.Complete.getValue())){
                      
                
               
                Object row [] = new Object[6];
                row[0] = nfpwr;
                row[1] = nfpwr.getRepresentative().getName();
                row[2] = nfpwr.getPerformanceInformation().getRiskRating();
                row[3] = nfpwr.getStatus();
                row[4] = nfpwr.getRepresentative().getName();
                if(nfpwr.getTrustee() != null)
                row[5] = nfpwr.getTrustee().getName();
                else
                row[5] = "";                 
                model.addRow(row); 
             
            }}
                
        }
        
         
         
        
    }
    
    public void populateBorrowerWorkTable()
    {
         DefaultTableModel model = (DefaultTableModel) tblBorrowerWorkCase.getModel();
         model.setRowCount(0);
         
         TrusteeOrganization trusteeOrg = business.getTrusteeOrganization();
         
         for(WorkRequest workRequest : trusteeOrg.getWorkQueue().getWorkRequestList())
         {
             if(workRequest instanceof NewLoanCaseWorkRequest)
                
             {NewLoanCaseWorkRequest nlcwr = (NewLoanCaseWorkRequest)workRequest;
                if(!nlcwr.getStatus().equals(NewLoanCaseWorkRequest.Status.Complete.getValue())){                
                   
                
                Object row [] = new Object[6];
                row[0] = nlcwr;
                row[1] = nlcwr.getLoan().getLoanCase().getCategory();
                row[2] = nlcwr.getLoan().getLoanCase().getLoanAmount();
                row[3] = nlcwr.getLoan().getLoanCase().getLoanLength();
                row[4] = nlcwr.getRepresentative().getName();
                if(nlcwr.getTrustee() != null)
                row[5] = nlcwr.getTrustee().getName();
                else
                row[5] = "";    
                model.addRow(row); 
             
                
                
             }}
                
         }
         
         
        
    }
    
    
    
    
    
    private void btnViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsActionPerformed
>>>>>>> 9f88221fa9a78811a4d9781a72be3543a6cb363c
        // TODO add your handling code here:
        HelpingHandsRevenueCollectionJPanel krcjp = new HelpingHandsRevenueCollectionJPanel(this.userProcessContainer, this.business);
        userProcessContainer.add("KivaRevenueCollectionJPanel", krcjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewRevenueActionPerformed

    private void btnBorrowerAssignToMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrowerAssignToMeActionPerformed
        // TODO add your handling code here:
       DefaultTableModel model = (DefaultTableModel) tblBorrowerWorkCase.getModel();
       int selectedRow = tblBorrowerWorkCase.getSelectedRow();
       if(selectedRow < 0){
           JOptionPane.showMessageDialog(null,  "Please select a row first","Information", JOptionPane.INFORMATION_MESSAGE);
           return ;
       }
       else
       {
           NewLoanCaseWorkRequest nlcwr = (NewLoanCaseWorkRequest)tblBorrowerWorkCase.getValueAt(selectedRow, 0);
        // Check if it is already assigned
        if(nlcwr.getTrustee() != null){
            JOptionPane.showMessageDialog(null, "Trustee already assigned", "Information", JOptionPane.INFORMATION_MESSAGE);
            return;
        }           
           nlcwr.setTrustee(trustee);
       }
       
       JOptionPane.showMessageDialog(null,"Work request assigned", "Information", JOptionPane.INFORMATION_MESSAGE);
       populateBorrowerWorkTable();
    }//GEN-LAST:event_btnBorrowerAssignToMeActionPerformed

    private void btnFieldPartnerAssignToMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFieldPartnerAssignToMeActionPerformed
        // TODO add your handling code here:
        
       DefaultTableModel model = (DefaultTableModel) tblFieldPartnerWorkCase.getModel();
       int selectedRow = tblFieldPartnerWorkCase.getSelectedRow();
       if(selectedRow < 0){
           JOptionPane.showMessageDialog(null,  "Please select a row first","Information", JOptionPane.INFORMATION_MESSAGE);
           return ;
       }
       else
       {
           NewFieldPartnerWorkRequest nfpwr = (NewFieldPartnerWorkRequest)tblFieldPartnerWorkCase.getValueAt(selectedRow, 0);
        if(nfpwr.getTrustee() != null){
            JOptionPane.showMessageDialog(null, "Trustee already assigned", "Information", JOptionPane.INFORMATION_MESSAGE);
            return;
        }           
           nfpwr.setTrustee(trustee);
       }
       JOptionPane.showMessageDialog(null,"Work request assigned", "Information", JOptionPane.INFORMATION_MESSAGE); 
       populateFieldPartnerWorkTable();
    }//GEN-LAST:event_btnFieldPartnerAssignToMeActionPerformed

    private void btnViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsActionPerformed
        // TODO add your handling code here:
        
       DefaultTableModel model = (DefaultTableModel) tblBorrowerWorkCase.getModel();
       int selectedRow = tblBorrowerWorkCase.getSelectedRow();
       if(selectedRow < 0)
       {
           JOptionPane.showMessageDialog(null, "Please select a row first","Information",  JOptionPane.INFORMATION_MESSAGE);
           return ;
       }
       else
       {
           NewLoanCaseWorkRequest nlcwr = (NewLoanCaseWorkRequest)tblBorrowerWorkCase.getValueAt(selectedRow, 0);
           if(nlcwr.getTrustee() != trustee){
           JOptionPane.showMessageDialog(null, "Please assign to yourself first", "Information", JOptionPane.INFORMATION_MESSAGE);
           return ;
        }
           
           TrusteeViewLoanCaseJPanel trusteeViewLoanCaseJPanel = new TrusteeViewLoanCaseJPanel(userProcessContainer,business,nlcwr);
           userProcessContainer.add("trusteeViewLoanCaseJPanel",trusteeViewLoanCaseJPanel);
           CardLayout layout = (CardLayout) userProcessContainer.getLayout();
           layout.next(userProcessContainer);
       }
        
    }//GEN-LAST:event_btnViewDetailsActionPerformed

    private void btnViewFieldPartnerDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewFieldPartnerDetailsActionPerformed
        // TODO add your handling code here:
<<<<<<< HEAD
        
       DefaultTableModel model = (DefaultTableModel) tblFieldPartnerWorkCase.getModel();
       int selectedRow = tblFieldPartnerWorkCase.getSelectedRow();
       if(selectedRow < 0)
       {
           JOptionPane.showMessageDialog(null, "Please select a row first","Information",  JOptionPane.INFORMATION_MESSAGE);
           return ;
       }
       else
       {
           NewFieldPartnerWorkRequest nfpwr = (NewFieldPartnerWorkRequest)tblFieldPartnerWorkCase.getValueAt(selectedRow, 0);
           if(nfpwr.getTrustee() != trustee){
           JOptionPane.showMessageDialog(null, "Please assign to yourself first", "Information", JOptionPane.INFORMATION_MESSAGE);
           return ;
        }           
           
           TrusteeViewFieldPartnerJPanel trusteeViewFieldPartnerJPanel = new TrusteeViewFieldPartnerJPanel(userProcessContainer,business,nfpwr);
           userProcessContainer.add("trusteeViewFieldPartnerJPanel",trusteeViewFieldPartnerJPanel);
           CardLayout layout = (CardLayout) userProcessContainer.getLayout();
           layout.next(userProcessContainer);
       }
        
        
    }//GEN-LAST:event_btnViewFieldPartnerDetailsActionPerformed
=======
        HelpingHandsRevenueCollectionJPanel hhrcjp = new HelpingHandsRevenueCollectionJPanel(this.userProcessContainer, this.business);
        userProcessContainer.add("HelpingHandsRevenueCollectionJPanel", hhrcjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
       
    }//GEN-LAST:event_btnViewHelpingHandsRevenueActionPerformed
>>>>>>> 9f88221fa9a78811a4d9781a72be3543a6cb363c

    private void btnViewFieldPartnerDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewFieldPartnerDetailsActionPerformed
        // TODO add your handling code here:

        DefaultTableModel model = (DefaultTableModel) tblFieldPartnerWorkCase.getModel();
        int selectedRow = tblFieldPartnerWorkCase.getSelectedRow();
        if(selectedRow < 0)
        {
            JOptionPane.showMessageDialog(null, "Please select a row first","Information",  JOptionPane.INFORMATION_MESSAGE);
            return ;
        }
        else
        {
            NewFieldPartnerWorkRequest nfpwr = (NewFieldPartnerWorkRequest)tblFieldPartnerWorkCase.getValueAt(selectedRow, 0);
            if(nfpwr.getTrustee() != trustee){
                JOptionPane.showMessageDialog(null, "Please assign to yourself first", "Information", JOptionPane.INFORMATION_MESSAGE);
                return ;
            }

            TrusteeViewFieldPartnerJPanel trusteeViewFieldPartnerJPanel = new TrusteeViewFieldPartnerJPanel(userProcessContainer,business,nfpwr);
            userProcessContainer.add("trusteeViewFieldPartnerJPanel",trusteeViewFieldPartnerJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }

    }//GEN-LAST:event_btnViewFieldPartnerDetailsActionPerformed

    private void btnFieldPartnerAssignToMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFieldPartnerAssignToMeActionPerformed
        // TODO add your handling code here:

        DefaultTableModel model = (DefaultTableModel) tblFieldPartnerWorkCase.getModel();
        int selectedRow = tblFieldPartnerWorkCase.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null,  "Please select a row first","Information", JOptionPane.INFORMATION_MESSAGE);
            return ;
        }
        else
        {
            NewFieldPartnerWorkRequest nfpwr = (NewFieldPartnerWorkRequest)tblFieldPartnerWorkCase.getValueAt(selectedRow, 0);
            if(nfpwr.getTrustee() != null){
                JOptionPane.showMessageDialog(null, "Trustee already assigned", "Information", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            nfpwr.setTrustee(trustee);
        }
        JOptionPane.showMessageDialog(null,"Work request assigned", "Information", JOptionPane.INFORMATION_MESSAGE);
        populateFieldPartnerWorkTable();
    }//GEN-LAST:event_btnFieldPartnerAssignToMeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrowerAssignToMe;
    private javax.swing.JButton btnFieldPartnerAssignToMe;
    private javax.swing.JButton btnViewDetails;
    private javax.swing.JButton btnViewFieldPartnerDetails;
<<<<<<< HEAD
    private javax.swing.JButton btnViewRevenue;
=======
    private javax.swing.JButton btnViewHelpingHandsRevenue;
>>>>>>> 9f88221fa9a78811a4d9781a72be3543a6cb363c
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblBorrowerWorkCase;
    private javax.swing.JTable tblFieldPartnerWorkCase;
    // End of variables declaration//GEN-END:variables
}
