/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.FieldPartnerRole;

import Business.Enterprise.HelpingHandsEnterprise;
import Business.Loan.Loan;
import Business.Loan.LoanCase;
import Business.Loan.LoanCase.Category;
import Business.Organization.BorrowerOrganization;
import Business.Organization.RepresentativeOrganization;
import Business.Person.Borrower;
import Business.Person.FieldPartnerContact;
import Business.Person.Person;
import Business.WorkQueue.NewLoanCaseWorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Leo
 */
public class AddBorrowersDetailsJPanel extends javax.swing.JPanel {

     private JPanel userProcessContainer ;
    private HelpingHandsEnterprise business ;
    private FieldPartnerContact fieldPartnerContact ;  
    
    /**
     * Creates new form AddBorrowersDetailsJPanel
     */
    public AddBorrowersDetailsJPanel() {
        initComponents();
    }
    
     public AddBorrowersDetailsJPanel(JPanel userProcessContainer, HelpingHandsEnterprise enterprise, FieldPartnerContact fieldPartnerContact) {
        initComponents();
        this.userProcessContainer = userProcessContainer ;
        this.business = enterprise ;
        this.fieldPartnerContact = fieldPartnerContact ;
        populateBorrowerComboBox();
        populateCategoryComboBox();
    }
    
    public void populateBorrowerComboBox(){
        Borrower borrower = null;
        borrowerComboBox.removeAllItems();
        BorrowerOrganization borrowerOrganization = business.getBorrowerOrganization();
        for(Person person : borrowerOrganization.getPersonDirectory().getPersonList()){
            borrower = (Borrower) person;
            if(business.getLoanDirectory().getBorrowerCurrentLoan(borrower) == null){
                borrowerComboBox.addItem(borrower);
            }
        }
    }
    
    public void populateCategoryComboBox(){
        categoryComboBox.removeAllItems();
        for(Category category : LoanCase.Category.values()){
            categoryComboBox.addItem(category);
        }
    }
    
    public void populateBorrowerLabels(Borrower borrower){
        txtBorrowerName.setText(borrower.getName());
        txtBorrowerPhoneNo.setText(borrower.getPhoneNo());
        txtBorrowerYearlyIncome.setText(String.valueOf(borrower.getYearlyIncome()));
        txtBorrowerEmailId.setText(borrower.getEmailId());
        txtBorrowerAddress.setText(borrower.getAddress());
        txtOccupation.setText(borrower.getOccupation());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtBorrowerName = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtStory = new javax.swing.JTextArea();
        txtBorrowerEmailId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtBorrowerPhoneNo = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtBorrowerAddress = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        txtOccupation = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtBorrowerYearlyIncome = new javax.swing.JTextField();
        borrowerComboBox = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnSubmitToRepresentative = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtLoanLength = new javax.swing.JTextField();
        categoryComboBox = new javax.swing.JComboBox();
        txtRepaymentMonthlyInstallment = new javax.swing.JTextField();
        txtRepaymentStartMonth = new javax.swing.JTextField();
        txtRepaymentStartYear = new javax.swing.JTextField();
        txtLoanAmount = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" NAME ");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 186, -1, -1));

        txtBorrowerName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        add(txtBorrowerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 186, 363, -1));

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText(" BORROWER DETAILS ");
        jLabel15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 63, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText(" LOAN CASE DETAILS ");
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(653, 118, 275, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MOTIVATION/STORY ");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(653, 163, 250, -1));

        txtStory.setColumns(20);
        txtStory.setRows(5);
        txtStory.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jScrollPane3.setViewportView(txtStory);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(654, 200, 317, 210));

        txtBorrowerEmailId.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        add(txtBorrowerEmailId, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 232, 363, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(" EMAIL ");
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 226, -1, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText(" PHONE ");
        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 271, -1, -1));

        txtBorrowerPhoneNo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        add(txtBorrowerPhoneNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 277, 363, -1));

        txtBorrowerAddress.setColumns(20);
        txtBorrowerAddress.setRows(5);
        txtBorrowerAddress.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jScrollPane2.setViewportView(txtBorrowerAddress);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 316, 359, 94));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText(" ADDRESS ");
        jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 316, -1, -1));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText(" WORKING ");
        jLabel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 441, -1, -1));

        jRadioButton1.setText("YES");
        add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 446, -1, -1));

        jRadioButton2.setText("NO");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 446, -1, -1));

        txtOccupation.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        add(txtOccupation, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 512, 366, -1));

        jLabel18.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText(" OCCUPATION ");
        jLabel18.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 506, -1, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText(" YEARLY INCOME ");
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 564, -1, -1));

        txtBorrowerYearlyIncome.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        add(txtBorrowerYearlyIncome, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 570, 285, -1));

        borrowerComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        borrowerComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowerComboBoxActionPerformed(evt);
            }
        });
        add(borrowerComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 620, 285, -1));

        jLabel16.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText(" SELECT BORROWER ");
        jLabel16.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 614, -1, -1));

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<< BACK");
        btnBack.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 192, 54));

        btnSubmitToRepresentative.setBackground(new java.awt.Color(0, 0, 0));
        btnSubmitToRepresentative.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        btnSubmitToRepresentative.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmitToRepresentative.setText("SUBMIT TO REPRESENTATIVE>> ");
        btnSubmitToRepresentative.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        btnSubmitToRepresentative.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitToRepresentativeActionPerformed(evt);
            }
        });
        add(btnSubmitToRepresentative, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 730, 410, 54));

        jLabel17.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel17.setText(" LOAN AMOUNT ");
        jLabel17.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(654, 700, -1, 24));

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel14.setText(" START YEAR ");
        jLabel14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(654, 657, -1, 24));

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel13.setText(" START MONTH ");
        jLabel13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(654, 620, -1, 24));

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel12.setText(" MONTHLY INSTALLMENT ");
        jLabel12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(654, 588, -1, 24));

        jLabel20.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText(" REPAYMENTS - ");
        jLabel20.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(654, 548, -1, -1));

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel11.setText(" CATEGORY ");
        jLabel11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(654, 505, -1, 24));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText(" LOAN LENGTH ");
        jLabel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(654, 432, -1, 24));

        txtLoanLength.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        add(txtLoanLength, new org.netbeans.lib.awtextra.AbsoluteConstraints(923, 435, 193, -1));

        categoryComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(categoryComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(923, 508, 193, -1));

        txtRepaymentMonthlyInstallment.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        add(txtRepaymentMonthlyInstallment, new org.netbeans.lib.awtextra.AbsoluteConstraints(923, 591, 193, -1));

        txtRepaymentStartMonth.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        add(txtRepaymentStartMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(923, 620, 193, -1));

        txtRepaymentStartYear.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        add(txtRepaymentStartYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(923, 660, 193, -1));

        txtLoanAmount.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        add(txtLoanAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(923, 700, 193, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void borrowerComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowerComboBoxActionPerformed
        // TODO add your handling code here:
        Borrower borrower = (Borrower) borrowerComboBox.getSelectedItem();
        if(borrower != null)
        { populateBorrowerLabels(borrower);}
    }//GEN-LAST:event_borrowerComboBoxActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSubmitToRepresentativeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitToRepresentativeActionPerformed
        // TODO add your handling code here:
        String story = txtStory.getText();
        int loanLength = Integer.parseInt(txtLoanLength.getText());
        Category category = (Category)categoryComboBox.getSelectedItem();
        int installment = Integer.parseInt(txtRepaymentMonthlyInstallment.getText());
        String startMonth = txtRepaymentStartMonth.getText();
        String startYear = txtRepaymentStartYear.getText();
        int loanAmount = Integer.parseInt(txtLoanAmount.getText());

        if(story == null ||
            loanLength == 0 ||
            installment == 0 || startMonth == null || startYear == null || loanAmount == 0){
            JOptionPane.showMessageDialog(null, "Please enter values in all fields","Information",  JOptionPane.INFORMATION_MESSAGE);
            return ;
        }

        Borrower borrower = (Borrower)borrowerComboBox.getSelectedItem();

        //Create a NewLoanCaseWorkRequest and send it to RepresentativeOrg Work Queue
        Loan loan = new Loan();
        LoanCase loanCase = new LoanCase();
        loanCase.setCaseDescripton(story);
        loanCase.setCategory(category);
        loanCase.setLoanLength(loanLength);
        loanCase.setLoanAmount(loanAmount);
        loanCase.setInstallment(installment);
        loanCase.setRepaymentStartMonth(startMonth);
        loanCase.setRepaymentStartYear(startYear);

        loan.setBorrower(borrower);
        loan.setFieldPartnerContact(fieldPartnerContact);
        loan.setLoanCase(loanCase);

        NewLoanCaseWorkRequest nlcwr = new NewLoanCaseWorkRequest();
        nlcwr.setBorrower(borrower);
        nlcwr.setLoan(loan);

        RepresentativeOrganization representativeOrganization = business.getRepresentativeOrganization();
        representativeOrganization.getWorkQueue().addWorkRequest(nlcwr);
        JOptionPane.showMessageDialog(null, "New Loan Case application sent to Representative for review","Information",  JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnSubmitToRepresentativeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox borrowerComboBox;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmitToRepresentative;
    private javax.swing.JComboBox categoryComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea txtBorrowerAddress;
    private javax.swing.JTextField txtBorrowerEmailId;
    private javax.swing.JTextField txtBorrowerName;
    private javax.swing.JTextField txtBorrowerPhoneNo;
    private javax.swing.JTextField txtBorrowerYearlyIncome;
    private javax.swing.JTextField txtLoanAmount;
    private javax.swing.JTextField txtLoanLength;
    private javax.swing.JTextField txtOccupation;
    private javax.swing.JTextField txtRepaymentMonthlyInstallment;
    private javax.swing.JTextField txtRepaymentStartMonth;
    private javax.swing.JTextField txtRepaymentStartYear;
    private javax.swing.JTextArea txtStory;
    // End of variables declaration//GEN-END:variables
}
