/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.FieldPartnerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HelpingHandsEnterprise;
import Business.Person.FieldPartnerContact;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import UserInterface.BorrowerSignUpJPanel;

/**
 *
 * @author Leo
 */
public class FieldPartnerWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private HelpingHandsEnterprise business ;
    private FieldPartnerContact fieldPartnerContact;
    
    /**
     * Creates new form FieldPartnerWorkAreaJPanel
     */
    public FieldPartnerWorkAreaJPanel() {
        initComponents();
    }
    
    public FieldPartnerWorkAreaJPanel(JPanel userProcessContainer, HelpingHandsEnterprise enterprise, FieldPartnerContact fieldPartnerContact) {
        initComponents();
        this.userProcessContainer = userProcessContainer ;
        this.business = enterprise ;
        this.fieldPartnerContact = fieldPartnerContact ;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCreateBorrower = new javax.swing.JButton();
        btnViewMyBorrower = new javax.swing.JButton();
        btnCreateBorrowerAccount = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 0, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCreateBorrower.setBackground(new java.awt.Color(153, 153, 153));
        btnCreateBorrower.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        btnCreateBorrower.setForeground(new java.awt.Color(51, 0, 51));
        btnCreateBorrower.setText("  CREATE BORROWER LOAN CASE >>  ");
        btnCreateBorrower.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        btnCreateBorrower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateBorrowerActionPerformed(evt);
            }
        });
        add(btnCreateBorrower, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, 61));

        btnViewMyBorrower.setBackground(new java.awt.Color(153, 153, 153));
        btnViewMyBorrower.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        btnViewMyBorrower.setForeground(new java.awt.Color(51, 0, 51));
        btnViewMyBorrower.setText("VIEW MY BORROWERS >>");
        btnViewMyBorrower.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        btnViewMyBorrower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewMyBorrowerActionPerformed(evt);
            }
        });
        add(btnViewMyBorrower, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 467, 58));

        btnCreateBorrowerAccount.setBackground(new java.awt.Color(153, 153, 153));
        btnCreateBorrowerAccount.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        btnCreateBorrowerAccount.setForeground(new java.awt.Color(51, 0, 51));
        btnCreateBorrowerAccount.setText("CREATE BORROWER ACCOUNT >>");
        btnCreateBorrowerAccount.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        btnCreateBorrowerAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateBorrowerAccountActionPerformed(evt);
            }
        });
        add(btnCreateBorrowerAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 467, 61));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FIELD PARTNER WORK AREA");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateBorrowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateBorrowerActionPerformed
        // TODO add your handling code here:
        AddBorrowersDetailsJPanel addBorrowersDetailsJPanel = new AddBorrowersDetailsJPanel(userProcessContainer, business, fieldPartnerContact);
        userProcessContainer.add("addBorrowersDetailsJPanel", addBorrowersDetailsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCreateBorrowerActionPerformed

    private void btnViewMyBorrowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewMyBorrowerActionPerformed
        // TODO add your handling code here:
        ViewMyBorrowersJPanel vmbjp = new ViewMyBorrowersJPanel(userProcessContainer, business, this.fieldPartnerContact);
        userProcessContainer.add("ViewMyBorrowersJPanel", vmbjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewMyBorrowerActionPerformed

    private void btnCreateBorrowerAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateBorrowerAccountActionPerformed
        // TODO add your handling code here:
        EcoSystem system = EcoSystem.getInstance();
        BorrowerSignUpJPanel signUpBorrowerJPanel = new BorrowerSignUpJPanel(userProcessContainer, system);
        userProcessContainer.add("BorrowerSignUpJPanel", signUpBorrowerJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCreateBorrowerAccountActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateBorrower;
    private javax.swing.JButton btnCreateBorrowerAccount;
    private javax.swing.JButton btnViewMyBorrower;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
