/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.BorrowerRole;

import Business.Enterprise.Enterprise;
import Business.Enterprise.HelpingHandsEnterprise;
import Business.Person.Borrower;
import static Business.Role.Role.RoleType.Borrower;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author shwetatatiya
 */
public class BorrowerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BorrowerWorkAreaJPanel
     */
    private JPanel userProcessContainer ;
    private Enterprise business ;
    private UserAccount userAccount ;
    private Borrower borrower ;
    public BorrowerWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise, UserAccount account, Borrower borrower) {
        initComponents();
        this.userProcessContainer = userProcessContainer ;
        this.business = enterprise ;
        this.userAccount = account ;
        this.borrower = borrower ;
    }
    
     public void populateCreditComboBox(){
        int[] amount = {25, 50, 100, 150, 200, 500, 1000, 1500, 1750, 2000, 5000};
        
        creditComboBox.removeAllItems();
        for(int i = 0; i<amount.length; i++){
            creditComboBox.addItem(amount[i]);
        }
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnViewLoancaseStatus = new javax.swing.JButton();
        btnRepayment = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        creditComboBox = new javax.swing.JComboBox();
        btnAddCredit = new javax.swing.JButton();
        txtCurrentBalance = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("  BORROWER DASHBOARD  ");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        btnViewLoancaseStatus.setBackground(new java.awt.Color(0, 0, 0));
        btnViewLoancaseStatus.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnViewLoancaseStatus.setForeground(new java.awt.Color(255, 255, 255));
        btnViewLoancaseStatus.setText("VIEW LOAN CASE STATUS >>");
        btnViewLoancaseStatus.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        btnViewLoancaseStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewLoancaseStatusActionPerformed(evt);
            }
        });
        add(btnViewLoancaseStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 320, 67));

        btnRepayment.setBackground(new java.awt.Color(0, 0, 0));
        btnRepayment.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnRepayment.setForeground(new java.awt.Color(255, 255, 255));
        btnRepayment.setText("REPAYMENT >> ");
        btnRepayment.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        btnRepayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepaymentActionPerformed(evt);
            }
        });
        add(btnRepayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 320, 61));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("  ADD CREDIT TO YOUR ACCOUNT");
        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, 330, 50));

        creditComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(creditComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 510, 182, -1));

        btnAddCredit.setForeground(new java.awt.Color(255, 255, 255));
        btnAddCredit.setText("ADD >>");
        btnAddCredit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        btnAddCredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCreditActionPerformed(evt);
            }
        });
        add(btnAddCredit, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 510, 94, 30));

        txtCurrentBalance.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        txtCurrentBalance.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        add(txtCurrentBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 650, 320, 60));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" CURRENT BALANCE AVAILABLE -");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 580, 330, 40));

        lblname.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblname.setForeground(new java.awt.Color(255, 255, 255));
        lblname.setText("name");
        add(lblname, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, -1, -1));

        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewLoancaseStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewLoancaseStatusActionPerformed
        // TODO add your handling code here:
        LoanCaseStatusJPanel loanCaseStatusJPanel = new LoanCaseStatusJPanel(userProcessContainer, (HelpingHandsEnterprise)business, borrower);
        userProcessContainer.add("loanCaseStatusJPanel", loanCaseStatusJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewLoancaseStatusActionPerformed

    private void btnRepaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepaymentActionPerformed
        // TODO add your handling code here:
        RepaymentJPanel repaymentJPanel = new RepaymentJPanel(userProcessContainer, (HelpingHandsEnterprise)business, borrower);
        userProcessContainer.add("RepaymentJPanel", repaymentJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnRepaymentActionPerformed

    private void btnAddCreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCreditActionPerformed
        // TODO add your handling code here:
        int amount = (int) creditComboBox.getSelectedItem();
        borrower.getAccountManagement().setAvailableCredit(borrower.getAccountManagement().getAvailableCredit() + amount);
        txtCurrentBalance.setText(String.valueOf(borrower.getAccountManagement().getAvailableCredit()));
        JOptionPane.showMessageDialog(null,  "Credit added successfully", "Information",JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnAddCreditActionPerformed

    public void populateCurrentBalance() {
        txtCurrentBalance.setText(String.valueOf(borrower.getAccountManagement().getAvailableCredit()));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCredit;
    private javax.swing.JButton btnRepayment;
    private javax.swing.JButton btnViewLoancaseStatus;
    private javax.swing.JComboBox creditComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblname;
    private javax.swing.JTextField txtCurrentBalance;
    // End of variables declaration//GEN-END:variables
}
